### ISSUE TITLE
Contact form fails to submit - "TypeError: 'User' object is not subscriptable"

### ISSUE THREAD

**Issue by proffalken** [tendenci/tendenci#1035]
When I try and submit the contact form at https://www.makemonmouth.co.uk/forms/contact-us/, the worker times out and the app logs are filled with the following (plus additional errors for other fields)

```
TIME="2021-08-30 20:12:07,680" LEVEL=DEBUG PID=7809 LOGGER="django.template" MSG="Exception while resolving variable 'impersonated_user' in template 'forms/form_detail.html'."
Traceback (most recent call last):
  File "/srv/tendenci/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/srv/tendenci/lib/python3.8/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
TypeError: 'User' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/tendenci/lib/python3.8/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/srv/tendenci/lib/python3.8/site-packages/django/utils/functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'impersonated_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/tendenci/lib/python3.8/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'impersonated_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/tendenci/lib/python3.8/site-packages/django/template/base.py", line 848, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [impersonated_user] in <SimpleLazyObject: <User: mmw>>
TIME="2021-08-30 20:12:07,685" LEVEL=DEBUG PID=7809 LOGGER="django.template" MSG="Exception while resolving variable 'theme' in template 'forms/form_detail.html'."
Traceback (most recent call last):
  File "/srv/tendenci/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/srv/tendenci/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 54, in __getitem__
    return self._session[key]
KeyError: 'theme'
```

I've rebuilt the cache, ensured that all the migrations are running etc.

I'm running `tendenci==12.5.8` installed via pip

**Comment by jennyq** [comment]
@proffalken Do you have the app and debug logging enabled in your `conf/setting`? If so, please disable them and only leave the console logging on.  Then restart the service to see if that fix the issue.

    disable_app_log()
    disable_debug_log()
    enable_console_log()

https://github.com/tendenci/tendenci-project-template/blob/master/conf/settings.py#L297

**Comment by proffalken** [comment]
@jennyq - made sure that all the logging was configured as per your comment.

The platform still errors, however I don't have any data in the logs to see why.

The Nginx log is as follows:

```
2021/08/31 06:13:14 [error] 814#814: *17 connect() failed (111: Connection refused) while connecting to upstream, client: <MY IP>, server: www.makemonmouth.co.uk, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8000/", host: "www.makemonmouth.co.uk"
2021/08/31 06:14:12 [error] 814#814: *19 upstream prematurely closed connection while reading response header from upstream, client: <MY IP>, server: www.makemonmouth.co.uk, request: "POST /forms/contact-us/ HTTP/1.1", upstream: "http://127.0.0.1:8000/forms/contact-us/", host: "www.makemonmouth.co.uk", referrer: "https://www.makemonmouth.co.uk/forms/contact-us/"
```

This suggests that there is an issue in Gunicorn timing out, however as I've disabled the application logging I'm unable to see where this error is occurring!

I've enabled DEBUG logging for Gunicorn, however all I see is the following:

```
==> /var/log/makemonmouth/access.log <==
127.0.0.1 - - [31/Aug/2021:07:19:24 +0100] "GET /captcha/image/1ca59551e0accf4f92bc5f997c073f555e932a8a/ HTTP/1.0" 200 14695 "https://www.makemonmouth.co.uk/forms/contact-us/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36"
127.0.0.1 - - [31/Aug/2021:07:19:26 +0100] "GET /files/76/ HTTP/1.0" 302 0 "https://www.makemonmouth.co.uk/forms/contact-us/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36"

==> /var/log/makemonmouth/server.log <==
[2021-08-31 07:19:29 +0100] [1715] [DEBUG] POST /forms/contact-us/
[2021-08-31 06:20:00 +0000] [1710] [CRITICAL] WORKER TIMEOUT (pid:1715)
[2021-08-31 07:20:00 +0100] [1715] [INFO] Worker exiting (pid: 1715)
[2021-08-31 06:20:00 +0000] [1786] [INFO] Booting worker with pid: 1786
```

**Comment by jennyq** [comment]
Try to restart your server after `conf/settings.py` is updated? 

Can you paste the result of `pip freeze`?

**Comment by proffalken** [comment]
Yup, all been restarted, pip freeze is as follows:

```
WARNING: Could not generate requirement for distribution -endenci 12.5.7 (/srv/tendenci/lib/python3.8/site-packages): Invalid requirement, parse error at "'-endenci'"
amqp==2.6.1
anyjson==0.3.3
arabic-reshaper==2.1.3
Authlib==0.14.3
beautifulsoup4==4.8.2
billiard==3.6.4.0
bleach==3.3.0
boto3==1.16.43
botocore==1.19.63
celery==4.4.0
certifi==2021.5.30
cffi==1.14.5
chardet==3.0.4
configparser==5.0.2
createsend==4.2.7
cryptography==3.4.7
dj-pagination==2.5.0
Django==2.2.24
django-admin-rangefilter==0.6.4
django-annoying==0.10.6
django-app-namespace-template-loader==0.4
django-authority==0.14
django-bootstrap-form==3.4
django-bootstrap3==12.0.3
django-countries==7.2.1
django-debug-toolbar==3.2.1
django-form-utils==1.0.3
django-formtools==2.3
django-haystack==2.8.1
django-localflavor==1.4.1
django-markdown-deux==1.0.5
django-nocaptcha-recaptcha==0.0.20
django-picklefield==3.0.1
django-ranged-response==0.2.0
django-ses==2.0.0
django-simple-captcha==0.5.12
django-sql-explorer==2.1.2
django-storages==1.11.1
django-tagging==0.4.6
django-tastypie==0.14.3
django-timezone-field==4.0
docutils==0.15.2
email-reply-parser==0.5.12
Embedly==0.5.0
feedparser==6.0.8
future==0.18.2
gevent==20.9.0
greenlet==1.1.0
gunicorn==20.0.4
html5lib==1.1
httplib2==0.19.1
idna==2.10
jmespath==0.10.0
kombu==4.6.11
Markdown==3.3.4
markdown2==2.4.0
mimeparse==0.1.3
nameparser==1.0.6
oauth2==1.9.0.post1
packaging==20.9
pdfminer.six==20170720
Pillow==8.3.1
pisa==3.0.33
psycopg2==2.8.6
pycparser==2.20
pycryptodome==3.9.6
pylibmc==1.6.1
pyparsing==2.4.7
PyPDF2==1.26.0
python-bidi==0.4.2
python-dateutil==2.8.1
python-magic==0.4.24
python-mimeparse==1.6.0
pytz==2019.3
raven==6.10.0
reportlab==3.5.68
requests==2.25.1
s3transfer==0.3.7
selenium==3.141.0
sgmllib3k==1.0.0
simple-salesforce==0.68.1
simplejson==3.17.2
six==1.16.0
soupsieve==2.2.1
sqlparse==0.4.1
stripe==2.42.0
tendenci==12.5.8
tendenci-django-admin-bootstrapped==4.0
unicodecsv==0.14.1
Unidecode==1.2.0
urllib3==1.26.6
vine==1.3.0
webcolors==1.11.1
webencodings==0.5.1
Whoosh==2.7.4
xhtml2pdf==0.2.5
xlrd==2.0.1
XlsxWriter==0.9.6
xlwt==1.3.0
zope.event==4.5.0
zope.interface==5.4.0
```

**Comment by jennyq** [comment]
That list looks fine except for the "WARNING" message. 

Does the timeout occur elsewhere besides the forms submissions?

**Comment by jennyq** [comment]
Have you configured the email settings? https://github.com/tendenci/tendenci-project-template/blob/master/conf/settings.py#L134
Is the password reset working? https://www.makemonmouth.co.uk/accounts/password/reset/

**Comment by proffalken** [comment]
Email settings have been configured to use Sendgrid, password reset form returns the same results.

Is there any particular reason why we need to turn *off* Debug logging to troubleshoot this? It feels counter-intuitive as surely the error messages will be in that log file?

**Comment by jennyq** [comment]
We want it to show relevant errors. The "enable_console_log()" in your conf/settings.py is suffice. The errors should be redirected to your server.log.  Other non-existent template variables can be safely ignored by Django (that's why we disabled the other two logs).

In your conf/settings.py, have you uncommented out those two settings and changed the `DEFAULT_FROM_EMAIL` to the same value as the no-reply site setting. If not, please update them and restart your service `service makemonmouth restart`.

    DEFAULT_FROM_EMAIL = 'no-reply@example.com'
    SERVER_EMAIL = DEFAULT_FROM_EMAIL

**Comment by jennyq** [comment]
If you still experience the issue after the above two settings are updated, you can monitor your log file while testing the form submission or password reset to find the real error. 

    tail -f /var/log/makemonmouth/server.log

**Comment by eschipul** [comment]
@jennyq the original error references the deprecated functionality of "impersonated_user"

`AttributeError: 'User' object has no attribute 'impersonated_user'`

That needs to be removed from the code everywhere.

**Comment by jennyq** [comment]
Thanks @eschipul ! I'll remove that `impersonated_user`.
