### ISSUE TITLE
Traceback Error - python manage.py deploy

### ISSUE THREAD

**Issue by W4JEW** [tendenci/tendenci#1106]
I've been trying to install Tendenci on a server running Ubuntu 20.04 LTS on Google Cloud Platform.

I installed Tendenci a few months ago without any issues. 

This time around, I keep running into an issue when I get to the point in the documentation where I cannot proceed any further:

[Tendenci Install - Basic Setup - Tendenci Preparation](https://tendenci.readthedocs.io/en/latest/installation/installation.html#tendenci-preparation)

In the section that starts off with:

"Initialize the database and static files:"

Per the instructions, within the virtualenv 'mysite', I run:

```
cd /var/www/mysite/
python manage.py initial_migrate
```
That completes without any errors.

Then I try to run:

```
python manage.py deploy
```

The output is as follows:

```
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/mysite/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/srv/mysite/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/mysite/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/mysite/lib/python3.8/site-packages/django/core/management/base.py", line 393, in execute
    self.check()
  File "/srv/mysite/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/srv/mysite/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/srv/mysite/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/srv/mysite/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/srv/mysite/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/srv/mysite/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/mysite/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/srv/mysite/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/mysite/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/mysite/conf/urls.py", line 6, in <module>
    from tendenci.urls import handler500  # noqa: F401
  File "/srv/mysite/lib/python3.8/site-packages/tendenci/urls.py", line 8, in <module>
    from tendenci.libs.model_report import report
  File "/srv/mysite/lib/python3.8/site-packages/tendenci/libs/model_report/report.py", line 22, in <module>
    from tendenci.libs.model_report.exporters.pdf import PdfExporter
  File "/srv/mysite/lib/python3.8/site-packages/tendenci/libs/model_report/exporters/pdf.py", line 4, in <module>
    from xhtml2pdf import pisa
  File "/srv/mysite/lib/python3.8/site-packages/xhtml2pdf/pisa.py", line 19, in <module>
    from xhtml2pdf.document import pisaDocument
  File "/srv/mysite/lib/python3.8/site-packages/xhtml2pdf/document.py", line 4, in <module>
    from xhtml2pdf.context import pisaContext
  File "/srv/mysite/lib/python3.8/site-packages/xhtml2pdf/context.py", line 11, in <module>
    import xhtml2pdf.parser
  File "/srv/mysite/lib/python3.8/site-packages/xhtml2pdf/parser.py", line 32, in <module>
    from xhtml2pdf.tables import *  # TODO: Kill wild import!
  File "/srv/mysite/lib/python3.8/site-packages/xhtml2pdf/tables.py", line 8, in <module>
    from xhtml2pdf.tags import pisaTag
  File "/srv/mysite/lib/python3.8/site-packages/xhtml2pdf/tags.py", line 10, in <module>
    from xhtml2pdf import xhtml2pdf_reportlab
  File "/srv/mysite/lib/python3.8/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 20, in <module>
    from reportlab.lib.utils import flatten, open_for_read, getStringIO, \
ImportError: cannot import name 'getStringIO' from 'reportlab.lib.utils' (/srv/mysite/lib/python3.8/site-packages/reportlab/lib/utils.py)
```

I'm not sure if this is an issue with the most current version of Tendenci and that's why I didn't encounter it the last time or what's going on?

I am not well-versed in Django, so I am unsure of how to resolve this issue. I would appreciate any advice you might have.

**Comment by W4JEW** [comment]
Actually, I think I figured out the issue. It appears as though there's a bug in reportlab (versions 3.6.7 through - at least - 3.6.9):

[Cannot import name 'getStringIO' from 'reportlab.lib.utils' #589](https://github.com/xhtml2pdf/xhtml2pdf/issues/589)

Per the recommendation, I installed reportlab==3.6.6 I used pip to install version 3.6.6 which downgraded the version installed during the Tendenci prerequisites installation (dev.txt or prod.txt) which was 3.6.9:

```
pip install reportlab==3.6.6
```

Once I confirmed that reportlab==3.6.6 was the currently installed version, I tried running:

```
python manage.py deploy
```

That time around, it was successful!

**Comment by jennyq** [comment]
Nice! Actually the fix has been pushed to the repo https://github.com/tendenci/tendenci/commit/265fc09115e8f51b7aa8621ee7c08e9472647bea. We'll do a version bump and push it to PYPI today.
