### ISSUE TITLE
Having trouble loading the database using "python manage.py initial_migrate"

### ISSUE THREAD

**Issue by sampushstack** [tendenci/tendenci#1119]
Hi

Help please, I am getting following error when following the basic setup instruction to run
`python manage.py initial_migrate`

```
(myaquatic) ubuntu@ip-172-31-19-204:/var/www/myaquatic$ python manage.py initial_migrate
/srv/myaquatic/lib/python3.8/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'tagging' defines default_app_config = 'tagging.apps.TaggingConfig'. Django now detects this configuration automatically. You can remove default_app_config.
  app_config = AppConfig.create(entry)

/srv/myaquatic/lib/python3.8/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'haystack' defines default_app_config = 'haystack.apps.HaystackConfig'. Django now detects this configuration automatically. You can remove default_app_config.
  app_config = AppConfig.create(entry)

/srv/myaquatic/lib/python3.8/site-packages/django_q/conf.py:139: UserWarning: Retry and timeout are misconfigured. Set retry larger than timeout, 
        failure to do so will cause the tasks to be retriggered before completion. 
        See https://django-q.readthedocs.io/en/latest/configure.html#retry for details.
  warn(

/srv/myaquatic/lib/python3.8/site-packages/explorer/apps.py:10: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
  verbose_name = _('SQL Explorer')

/srv/myaquatic/lib/python3.8/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'explorer' defines default_app_config = 'explorer.apps.ExplorerAppConfig'. Django now detects this configuration automatically. You can remove default_app_config.
  app_config = AppConfig.create(entry)

Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/myaquatic/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/srv/myaquatic/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/srv/myaquatic/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/myaquatic/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/srv/myaquatic/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/myaquatic/lib/python3.8/site-packages/tendenci/libs/tinymce/models.py", line 6, in <module>
    from tendenci.libs.tinymce import widgets as tinymce_widgets
  File "/srv/myaquatic/lib/python3.8/site-packages/tendenci/libs/tinymce/widgets.py", line 24, in <module>
    import tendenci.libs.tinymce.settings as tinymce_settings
  File "/srv/myaquatic/lib/python3.8/site-packages/tendenci/libs/tinymce/settings.py", line 16, in <module>
    JS_URL = static(getattr(settings, 'TINYMCE_JS_URL', 'tiny_mce/tiny_mce.js'))
  File "/srv/myaquatic/lib/python3.8/site-packages/tendenci/apps/theme/templatetags/static.py", line 115, in static
    return ThemeStaticNode.handle_simple(path, local_only)
  File "/srv/myaquatic/lib/python3.8/site-packages/tendenci/apps/theme/templatetags/static.py", line 53, in handle_simple
    for cur_theme in get_theme_search_order(theme):
  File "/srv/myaquatic/lib/python3.8/site-packages/tendenci/apps/theme/utils.py", line 131, in get_theme_search_order
    theme_search_order = cache.get(cache_key)
  File "/srv/myaquatic/lib/python3.8/site-packages/django/core/cache/backends/memcached.py", line 77, in get
    return self._cache.get(key, default)
  File "/srv/myaquatic/lib/python3.8/site-packages/pymemcache/client/hash.py", line 361, in get
    return self._run_cmd('get', key, default, default=default, **kwargs)
  File "/srv/myaquatic/lib/python3.8/site-packages/pymemcache/client/hash.py", line 334, in _run_cmd
    return self._safely_run_func(
  File "/srv/myaquatic/lib/python3.8/site-packages/pymemcache/client/hash.py", line 214, in _safely_run_func
    result = func(*args, **kwargs)
  File "/srv/myaquatic/lib/python3.8/site-packages/pymemcache/client/base.py", line 619, in get
    return self._fetch_cmd(b'get', [key], False).get(key, default)
  File "/srv/myaquatic/lib/python3.8/site-packages/pymemcache/client/base.py", line 1018, in _fetch_cmd
    self._connect()
  File "/srv/myaquatic/lib/python3.8/site-packages/pymemcache/client/base.py", line 420, in _connect
    sock.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused


```

**Comment by Pandaski** [comment]
Exactly the same error here.

**Comment by Pandaski** [comment]
OS
```
Linux version 5.4.0-122-generic (buildd@bos02-arm64-075) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #138-Ubuntu SMP Wed Jun 22 15:05:39 UTC 2022
```

Python
```
Python 3.8.10
```

Django
```
Name: Django
Version: 3.2.14
```
Followed https://tendenci.readthedocs.io/en/latest/installation/installation.html#database-preparation to install Tendenci on my newly created VM and get the error when running `python manage.py initial_migrate`

**Comment by jennyq** [comment]
Hi @sampushstack and @Pandaski,

Thank you for reporting the issue! A fix has been pushed to https://github.com/tendenci/tendenci-project-template/. You can add the [DummyCache](https://github.com/tendenci/tendenci-project-template/blob/master/conf/settings.py#L230) in your conf/settings.py `CACHES['default']['BACKEND'] = 'django.core.cache.backends.dummy.DummyCache'` or re-run the command `tendenci startproject mysite`. Let me know how that work for you.

**Comment by sampushstack** [comment]
Great this fixed it :) thanks Jenny

**Comment by Pandaski** [comment]
Fixed. Super thanks for the quick response!

**Comment by jennyq** [comment]
Great!

**Comment by ndumisony** [comment]
> Fixed. Super thanks for the quick response!

I am facing the same issue, please assist.
