### ISSUE TITLE
Amazon SES newsletter send fails if a recipient email address is "unverified"

### ISSUE THREAD

**Issue by rob-hills** [tendenci/tendenci#1198]
We are trying to test newsletter sending using Amazon SES.  This is primarily to establish if issue #1150
is caused by a Tendenci bug or by our SMTP host Mailgun.

After setting up our Amazon SES account, it remains in the Asia Pacific (Sydney) sandbox.  This means we can only send emails via this service to "verified" email addresses.

We tried sending a newsletter to a small group that contained a mix of verified and unverified email addresses.  This newsletter fails to send and its status on the Newsletter page seems to be locked on "Sending".  It appears that the error triggered by Amazon SES rejecting the unverified address.

Is this how it is meant to work?  I'd have expected it to skip past this email address and send to next.

Here is the traceback...

```
Error sending newsletter https://aeva.asn.au/newsletters/view/details/1051/
...

Traceback (most recent call last):
  File "/srv/tendenci_test/environment.py-3.8/src/tendenci/tendenci/apps/newsletters/management/commands/send_newsletter.py", line 216, in handle
    self.send_newsletter(newsletter_id)
  File "/srv/tendenci_test/environment.py-3.8/src/tendenci/tendenci/apps/newsletters/management/commands/send_newsletter.py", line 149, in send_newsletter
    email_to_send.send(connection=3Dconnection)
  File "/srv/tendenci_test/environment.py-3.8/src/tendenci/tendenci/apps/emails/models.py", line 130, in send
    msg.send(fail_silently=3Dfail_silently)
  File "/srv/tendenci_test/environment.py-3.8/lib/python3.8/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/srv/tendenci_test/environment.py-3.8/lib/python3.8/site-packages/django_ses/__init__.py", line 168, in send_messages
    else self.connection.send_raw_email(**kwargs))
  File "/srv/tendenci_test/environment.py-3.8/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/srv/tendenci_test/environment.py-3.8/lib/python3.8/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.MessageRejected: An error occurred (MessageRejected) when calling the SendRawEmail operation: Email address is not verified. The following identities failed the check in region AP-SOUTHEAST-2: cw????@?????.com.au
```

**Comment by jennyq** [comment]
Yes, it is expected behavior. Once you're out of the sandbox, you shouldn't receive this error. 

However, I'm not sure if Amazon SES also throws errors for undeliverable email addresses. If so, the newsletter send should catch those errors and continue with the next.

**Comment by rob-hills** [comment]
Unfortunately it makes it difficult to test things while still in the sandbox.

We're keen to avoid accidentally spamming large numbers of members with test messages so have been avoiding moving AWS into production mode until we've confirmed everything works properly.

Is it possible to have Tendenci handle this error the same way it handles other errors that are associated with a specific email address?  IOW record the fact that the message couldn't be delivered together with the reason?

**Comment by jennyq** [comment]
Wait, I'll take that back. Pretty sure AWS SES doesn't throw errors for undeliverable email addresses.

**Comment by rob-hills** [comment]
It appears that the exception originates from the botocore interface.  Should we be approaching whoever manages botocore about this?

**Comment by jennyq** [comment]
The botocore does the right thing - "Errors should never pass silently."

For the test purpose, you can edit the file tendenci/apps/emails/models.py directly to set `fail_silently` to True for the `send` method in the `Email` class.

**Comment by rob-hills** [comment]
I agree that exceptions should never pass silently.

However I would argue that invalid email addresses in a batch email process are to be **expected** and therefore aren't errors. IMHO they should be logged without interrupting the process.

This is an unusual issue that will likely only arise in a testing situation, but in our case it has prevented us from being able to test within our testing environment. Instead we were forced to go live and complete our testing with the production environment configured in Amazon SES.

Not being able to use a test environmental properly suggests a flaw somewhere I think.

Anyway it's a rare event so likely low priority.

**Comment by jennyq** [comment]
Agreed "they should be logged without interrupting the process". Feel free to submit a pull request.
