### ISSUE TITLE
Upgrade to Tendenci 15.0 fails "cannot import name 'smart_text' from 'django.utils.encoding'"

### ISSUE THREAD

**Issue by rob-hills** [tendenci/tendenci#1270]
Following [the upgrade instructions](https://tendenci.readthedocs.io/en/latest/upgrade/upgrade-to-tendenci.html), I created a new environment (Python 3.8.12) and installed Tendenci into that, using the requirements/dev.txt requirements file.

However, when I tried to run "migrate" it failed with the following Traceback:
```
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/tagging/models.py", line 8, in <module>
    from django.utils.encoding import smart_text
ImportError: cannot import name 'smart_text' from 'django.utils.encoding' (/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/utils/encoding.py)
(environment.tendenci-15) root@volume-genetic:/srv/tendenci_test/website# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/tagging/models.py", line 8, in <module>
    from django.utils.encoding import smart_text
ImportError: cannot import name 'smart_text' from 'django.utils.encoding' (/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/utils/encoding.py)
```

Googling this error indicates that "smart_text" in django.utils.encoding has been replaced by "smart_str".  However, I don't understand how an error like this hasn't cropped up in earlier testing of this upgrade process so I wonder if I'm doing something wrong somewhere?

The workaround noted in https://stackoverflow.com/questions/71589827/i-have-an-error-about-smart-text-after-installing-django-admin-charts seems to resolve this error, but it seems to be a bit of a kludge!

Cheers,

Rob

**Comment by jennyq** [comment]
@rob-hills,

Can you please check what's in your env?

    pip freeze

Also, check the content of your requirements/tendenci.txt, requirements/dev.txt, please.

    cat requirements/dev.txt
    cat requirements/tendenci.txt

**Comment by rob-hills** [comment]
pip freeze
```
amqp==5.2.0
annotated-types==0.6.0
arabic-reshaper==3.0.0
arrow==1.3.0
asgiref==3.8.1
asn1crypto==1.5.1
attrs==23.2.0
Authlib==0.15.4
backports.zoneinfo==0.2.1
beautifulsoup4==4.9.3
billiard==3.6.4.0
bleach==6.1.0
blessed==1.20.0
boto3==1.29.3
botocore==1.32.7
cachetools==5.3.3
cchardet==2.1.7
celery==5.2.3
certifi==2024.2.2
cffi==1.16.0
chardet==4.0.0
charset-normalizer==3.3.2
click==8.1.7
click-didyoumean==0.3.1
click-plugins==1.1.1
click-repl==0.3.0
configparser==6.0.1
createsend==6.1.2
cryptography==42.0.5
cssselect2==0.7.0
defusedxml==0.7.1
dj-pagination==2.5.0
Django==3.2.25
django-admin-rangefilter==0.8.1
django-annoying==0.10.6
django-apptemplates==1.5
django-authority==0.14
django-bootstrap-form==3.4
django-bootstrap3==15.0.0
django-countries==7.2.1
django-debug-toolbar==4.3.0
django-formtools==2.5.1
django-haystack==3.0
django-localflavor==3.1
django-log-email @ git+https://github.com/PaulSD/django_log_email@358b292f3dd73a92919c5005379cc4f6eadcb5ae
django-markdown-deux==1.0.6
django-model-utils==4.5.0
django-otp==1.3.0
django-phonenumber-field==7.3.0
django-picklefield==3.2
django-q==1.3.9
django-q2==1.6.1
django-qr-code==3.1.1
django-ranged-response==0.2.0
django-ses==3.5.0
django-simple-captcha==0.5.20
django-sql-explorer==2.1.2
django-storages==1.12.3
django-tagging==0.5.0
django-tastypie==0.14.3
django-timezone-field==4.2.1
django-two-factor-auth==1.16.0
docutils==0.17.1
email-reply-parser==0.5.12
exceptiongroup==1.2.0
feedparser==6.0.11
future==1.0.0
gevent==23.9.1
greenlet==3.0.3
gunicorn==20.1.0
h11==0.14.0
html5lib==1.1
httplib2==0.22.0
idna==3.6
importlib_metadata==7.1.0
importlib_resources==6.4.0
isodate==0.6.1
jmespath==1.0.1
kombu==5.3.6
lxml==4.9.1
Markdown==3.3.4
markdown2==2.4.13
mimeparse==0.1.3
model-bakery==1.17.0
more-itertools==10.2.0
nameparser==1.1.3
oauth2==1.9.0.post1
oscrypto==1.3.0
outcome==1.3.0.post0
packaging==24.0
pdfminer.six==20201018
pendulum==3.0.0
phonenumbers==8.13.34
pillow==10.2.0
pkg_resources==0.0.0
platformdirs==4.2.0
prompt-toolkit==3.0.43
psycopg2==2.9.1
pycparser==2.22
pycryptodome==3.19.1
pydantic==2.6.4
pydantic_core==2.16.3
pyHanko==0.23.2
pyhanko-certvalidator==0.26.3
PyJWT==2.8.0
pymemcache==4.0.0
pyparsing==3.1.2
pypdf==4.1.0
pypng==0.20220715.0
PySocks==1.7.1
python-bidi==0.4.2
python-dateutil==2.8.2
python-magic==0.4.27
python-mimeparse==1.6.0
python-stdnum==1.20
python3-openid==3.2.0
pytz==2021.3
PyYAML==6.0.1
pyzoom==1.0.8
qrcode==7.4.2
raven==6.10.0
redis==3.5.3
reportlab==3.6.13
requests==2.31.0
requests-file==2.0.0
requests-toolbelt==1.0.0
s3transfer==0.7.0
segno==1.6.1
selenium==3.141.0
sgmllib3k==1.0.0
shortuuid==1.0.13
simple-salesforce==1.11.2
simplejson==3.19.2
six==1.16.0
sniffio==1.3.1
sortedcontainers==2.4.0
soupsieve==2.5
sqlparse==0.4.4
stripe==2.60.0
svglib==1.5.1
tendenci==14.8.2
tendenci-django-admin-bootstrapped==5.2
tendenci-django-tagging==0.6
time-machine==2.14.1
tinycss2==1.2.1
trio==0.25.0
trio-websocket==0.11.1
types-python-dateutil==2.9.0.20240316
typing_extensions==4.11.0
tzdata==2024.1
tzlocal==5.2
unicodecsv==0.14.1
Unidecode==1.3.8
uritools==4.0.2
urllib3==1.26.18
vine==5.1.0
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
Whoosh==2.7.4
wsproto==1.2.0
xhtml2pdf==0.2.11
xlrd==2.0.1
xlrd3==1.1.0
XlsxWriter==1.4.4
xlwt==1.3.0
zeep==4.2.1
zipp==3.18.1
zope.event==5.0
zope.interface==6.2
```

**Comment by rob-hills** [comment]
cat requirements/tendenci.txt 
```
# https://github.com/tendenci/tendenci/archive/master.zip
# gevent>=1.4.0
# tendenci>=12,<12.5.4
# tendenci>=14.8,<14.9
tendenci>=15,<16
```

cat requirements/dev.txt 
```
-r common.txt
-r tendenci.txt
```

**Comment by jennyq** [comment]
It's weird - why do you have `Django==3.2.25` installed? The version of Django should be on 4.2 LTS https://github.com/tendenci/tendenci/blob/main/requirements.txt#L4

**Comment by rob-hills** [comment]
This problem ended up being due to user error!
