### ISSUE TITLE
Upgrade to Tendenci 15.0 fails "No module named 'zoneinfo'"

### ISSUE THREAD

**Issue by rob-hills** [tendenci/tendenci#1271]
After using the workaround to resolve #1270, my next attempt to run "migrate" failed again, this time with an import error:

```
(environment.tendenci-15) root@volume-genetic:/srv/tendenci_test/website# python manage.py migrate
/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django_q/core_signing.py:9: RemovedInDjango50Warning: The django.utils.baseconv module is deprecated.
  from django.utils import baseconv

/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/haystack/fields.py:5: RemovedInDjango50Warning: The django.utils.datetime_safe module is deprecated.
  from django.utils import datetime_safe

Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/tendenci_test/website/conf/urls.py", line 6, in <module>
    from tendenci.urls import handler500  # noqa: F401
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/tendenci/urls.py", line 135, in <module>
    path('qr_code/', include('qr_code.urls', namespace="qr_code")),
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/qr_code/urls.py", line 4, in <module>
    from qr_code import views
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/qr_code/views.py", line 13, in <module>
    from qr_code.qrcode.maker import make_qr_code_image
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/qr_code/qrcode/maker.py", line 13, in <module>
    from qr_code.qrcode.serve import make_qr_code_url
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/qr_code/qrcode/serve.py", line 17, in <module>
    from qr_code.qrcode.utils import QRCodeOptions
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/qr_code/qrcode/utils.py", line 11, in <module>
    import zoneinfo
ModuleNotFoundError: No module named 'zoneinfo'
```

Googling this problem suggested that the ZoneInfo module is new to Python 3.9 (we're on 3.8) but can be backported.

Interpolating from the kludge used to fix #1270, I tried the following in our settings.py:
```
from backports.zoneinfo import ZoneInfo
zoneinfo = ZoneInfo
```

But I still get the same error and traceback.

Is Tendenci 15 dependent on Python 3.9?

**Comment by jennyq** [comment]
It's an issue in the latest version of django-qr-code. Fixed it by pinning django-qr-code to 3.1.1 for now. https://github.com/tendenci/tendenci/commit/2652f86cc2b594891f408571765d82362b1e4a54.
