### ISSUE TITLE
Tendenci 15: ImportError: cannot import name 'url' from 'django.conf.urls'

### ISSUE THREAD

**Issue by rob-hills** [tendenci/tendenci#1273]
Still trying to get Tendenci 15 running on our test server.

This exception occurs when trying to run migrate.py

```
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/tendenci_test/website/conf/urls.py", line 8, in <module>
    from django.conf.urls import url, include  # noqa: F401
ImportError: cannot import name 'url' from 'django.conf.urls' (/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/conf/urls/__init__.py)
```

The offending file `/srv/tendenci_test/website/conf/urls.py` has this comment at the top:
```
# This file is ignored unless "ROOT_URLCONF = 'conf.urls'" is configured in
# settings.py
```

When I checked our `settings.py` file, sure enough, our ROOT_URLCONF is indeed set to 'conf.urls'

Looking at the code in `/srv/tendenci_test/website/conf/urls.py` , the imported functions "url" and "include" aren't used anyway so I commented out this import line
```
from django.conf.urls import url, include  # noqa: F401
```
and the Migrate command ran through without any further errors!

**Comment by jennyq** [comment]
We've updated the docs after tristanjl pointed out in the issue https://github.com/tendenci/tendenci/issues/1269.
