### ISSUE TITLE
Error when editing Places from Admin Backend

### ISSUE THREAD

**Issue by b-davies24** [tendenci/tendenci#1310]
The new feature to be able to edit/merge/delete places in the Events database partially works; merging/deleting works fine, however, this error is thrown up when I try to edit (e.g. edit the name of the state) of the place:
![image](https://github.com/user-attachments/assets/db3c3b23-bfe7-4bf0-a5e9-859369cb803e)

What could be causing this?

**Comment by rob-hills** [comment]
The following seems to be a log entry (with traceback) for one of these errors:
```
TIME="2024-09-15 20:57:43,046" LEVEL=ERROR PID=3548980 LOGGER="django.request" MSG="Internal Server Error: /admin/events/place/440/change/"
Traceback (most recent call last):
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/srv/tendenci_test/environment.tendenci-15/src/tendenci/tendenci/apps/perms/admin.py", line 113, in change_view
    result = super(TendenciBaseModelAdmin, self).change_view(
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/srv/tendenci_test/environment.tendenci-15/src/tendenci/tendenci/apps/perms/admin.py", line 99, in save_model
    instance = update_perms_and_save(request, form, instance, log=False)
  File "/srv/tendenci_test/environment.tendenci-15/src/tendenci/tendenci/apps/perms/utils.py", line 75, in update_perms_and_save
    instance.save(**kwargs)
TypeError: save() got an unexpected keyword argument 'log'

```
