### ISSUE TITLE
Renewing a directory causes 403 error

### ISSUE THREAD

**Issue by rob-hills** [tendenci/tendenci#1312]
We have an issue with Directories going out of date and today tried the "Renew Directory" function to resolve this via the Tendenci interface.  Unfortunately this results in a 403 error.

In the following traceback, I am mystified by the URL in the "Invalid HTTP_HOST header" (cloudfare-resolve-to.aeva.asn.au).  The correct URL should actually be "test.aeva.asn.au" so I don't think I should be adding "cloudfare-resolve-to.aeva.asn.au" to our ALLOWED_HOSTS list as recommended.  @jennyq is this a setting we have wrong somewhere or is it a bug in Tendenci?  Googling hasn't revealed anything helpful.

Here is the Traceback:
```
TIME="2024-09-22 08:24:35,268" LEVEL=ERROR PID=660361 LOGGER="django.security.DisallowedHost" MSG="Invalid HTTP_HOST header: 'cloudflare-resolve-to.aeva.asn.au'. You may need to add 'cloudflare-resolve-to.aeva.asn.au' to ALLOWED_HOSTS."
Traceback (most recent call last):
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/srv/tendenci_test/environment.tendenci-15/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'cloudflare-resolve-to.aeva.asn.au'. You may need to add 'cloudflare-resolve-to.aeva.asn.au' to ALLOWED_HOSTS.
TIME="2024-09-22 08:24:35,350" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Bad Request: /"
TIME="2024-09-22 09:11:01,986" LEVEL=WARNING PID=660359 LOGGER="django.request" MSG="Not Found: /events/print-view/523/"
TIME="2024-09-22 09:29:30,772" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /favicon.ico"
TIME="2024-09-22 09:33:39,481" LEVEL=WARNING PID=660362 LOGGER="django.request" MSG="Not Found: /clients/MyCRL/"
TIME="2024-09-22 09:34:07,701" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /clients/MyCRL/"
TIME="2024-09-22 10:38:02,472" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /wp-includes/ID3/license.txt"
TIME="2024-09-22 10:38:03,872" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /feed/"
TIME="2024-09-22 10:38:05,560" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /blog/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 10:38:06,957" LEVEL=WARNING PID=660362 LOGGER="django.request" MSG="Not Found: /web/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 10:38:08,344" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /wordpress/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 10:38:09,684" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /wp/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 10:38:11,335" LEVEL=WARNING PID=660362 LOGGER="django.request" MSG="Not Found: /2020/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 10:38:12,609" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /2019/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 10:38:13,935" LEVEL=WARNING PID=660363 LOGGER="django.request" MSG="Not Found: /2021/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 10:38:15,207" LEVEL=WARNING PID=660359 LOGGER="django.request" MSG="Not Found: /shop/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 10:38:16,458" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /wp1/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 10:38:17,973" LEVEL=WARNING PID=660362 LOGGER="django.request" MSG="Not Found: /test/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 10:38:19,774" LEVEL=WARNING PID=660362 LOGGER="django.request" MSG="Not Found: /site/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 10:38:21,177" LEVEL=WARNING PID=660362 LOGGER="django.request" MSG="Not Found: /cms/wp-includes/wlwmanifest.xml"
TIME="2024-09-22 11:30:23,719" LEVEL=WARNING PID=660363 LOGGER="django.request" MSG="Not Found: /webui/"
TIME="2024-09-22 11:34:08,241" LEVEL=WARNING PID=660363 LOGGER="django.request" MSG="Not Found: /favicon.ico"
TIME="2024-09-22 11:38:29,545" LEVEL=WARNING PID=660359 LOGGER="django.request" MSG="Not Found: /geoserver/web/"
TIME="2024-09-22 11:54:29,943" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /ai.txt"
TIME="2024-09-22 12:24:17,175" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /level/15/exec/-/sh/run/CR/"
TIME="2024-09-22 13:16:40,461" LEVEL=WARNING PID=660361 LOGGER="django.request" MSG="Not Found: /articles/firstname-ev-council-presentation-for-world-ev-day/[unsubscribe_url]"
TIME="2024-09-22 15:02:16,994" LEVEL=WARNING PID=660363 LOGGER="django.request" MSG="Not Found: /newsletters/view/105/[unsubscribe_url]"
TIME="2024-09-22 15:43:18,102" LEVEL=WARNING PID=660363 LOGGER="django.request" MSG="Not Found: /articles/warwick-trip/"

```

**Comment by jennyq** [comment]
Hmm.. no idea. Maybe the url "cloudflare-resolve-to.aeva.asn.au" is linked somewhere on your site? Looks like the "DisallowedHost" error is **not** relevant to the directory renewal.
