### ISSUE TITLE
You need to specify NAME in your Django settings file.

### ISSUE THREAD

**Issue by shoffer** [tendenci/tendenci#362]
I have Linode UBUNTU 14.04 LTS and followed the instructions here:
https://tendenci.readthedocs.org/en/latest/installation/remote.html
5 times...3 times with the recommended 14.04 LTS...but I error out at the python deploy.py with :
~~~~~~~~
Skipping creation of NoticeTypes as notification app not found
Syncing...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/var/www/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/var/www/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/var/www/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/var/www/tendenci/venv/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 90, in handle_noargs
    syncdb.Command().execute(**options)
  File "/var/www/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/var/www/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
    return self.handle_noargs(**options)
  File "/var/www/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 57, in handle_noargs
    cursor = connection.cursor()
  File "/var/www/tendenci/venv/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 319, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/var/www/tendenci/venv/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 162, in _cursor
    raise ImproperlyConfigured("You need to specify NAME in your Django settings file.")
django.core.exceptions.ImproperlyConfigured: You need to specify NAME in your Django settings file.
Traceback (most recent call last):
  File "deploy.py", line 3, in <module>
    subprocess.check_call(['python', 'manage.py',  'syncdb', '--noinput'])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'syncdb', '--noinput']' returned non-zero exit status 1
~~~~~~~~
Any ideas? I am really excited to try out tendenci.

Thank...Steve

**Comment by eschipul** [comment]
Steve,

I left you at this point 
https://tendenci.readthedocs.org/en/latest/installation/remote.html#setting-up-upstart

The db is all set up. It was the connection string in .env which as I mentioned is a hangover from our attempts to work with heroku (mistake). The .env goes away in tendenci 6 but right now it is configured correctly. I created a new database and a new database user for you to avoid conflicts. The db and the db user I will send by email.

It is NOT done as you will need to continue from the setting up upstart portion but you are through the migrations etc.... It should be downhill from here but if not you know how to reach me.

I'll email the config vars.

And again - be sure to change that password! In fact turn off password auth and just use ssh.

Thanks,

Ed
