### ISSUE TITLE
AES key must be either 16, 24, or 32 bytes long

### ISSUE THREAD

**Issue by siolag161** [tendenci/tendenci#364]
I just tried out the `version 6` of `tendenci` in `debug` mode and it welcome me with this message. Probably due to this line in the `local_settings.py` file

```python
    SITE_SETTINGS_KEY='tendenci_site_key_bdc635k2-283d-4a2c-a477-339ea866'
```
I changed the value to `0123456701234567` (16 bits) then the error went away.

What do you think? Maybe python2 vs python3 ?

**Comment by eschipul** [comment]
Hmmmm, well you are definitely supposed to update the site_settings_key as that is a layer of protection beyond the base password level that we all know we can't count on users to make unique. But the default should not have thrown an error either.

Did you start your project using the https://github.com/tendenci/tendenci-project-template

e.g.

       django-admin.py startproject --template=https://github.com/tendenci/tendenci-project-template/zipball/master <project_name>

**Comment by siolag161** [comment]
I did find it strange too. I had some spare time to I did it again on my other PC and got the exact result.

Here I stimulate the code in your  `tendenci/apps/site_settings/utils.py` as I don't know your unit test works

```python
>>> from Crypto.Cipher import AES
>>> len("tendenci_site_key_bdc635k2-283d-4a2c-a477-339ea866")
50
>>> setting_key = "tendenci_site_key_bdc635k2-283d-4a2c-a477-339ea866"
>>> cipher = AES.new(setting_key, AES.MODE_ECB)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/Crypto/Cipher/AES.py", lin
e 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/Crypto/Cipher/AES.py", lin
e 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/Crypto/Cipher/blockalgo.py
", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: AES key must be either 16, 24, or 32 bytes long
>>> 

```
So `pycrypto` does not like string of arbitrary length.

Here is the full trackback

```python

[24/Mar/2015 16:30:43] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    mw_instance = mw_class()
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/siolag161/tmp/tendenci/conf/urls.py", line 4, in <module>
    from tendenci.urls import urlpatterns as tendenci_urls
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/tendenci/urls.py", line 11, in <module>
    admin.autodiscover()
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/tendenci/apps/forms_builder/forms/admin.py", line 23, in <module>
    from tendenci.apps.forms_builder.forms.forms import FormAdminForm, FormForField, PricingForm
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/tendenci/apps/forms_builder/forms/forms.py", line 35, in <module>
    template_choices += get_template_list()
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/tendenci/apps/base/utils.py", line 564, in get_template_list
    theme = get_setting('module', 'theme_editor', 'theme')
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/tendenci/apps/site_settings/utils.py", line 350, in get_setting
    value = setting.get_value().strip()
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/tendenci/apps/site_settings/models.py", line 59, in get_value
    return decrypt(self.value).decode('utf-8')
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/tendenci/apps/site_settings/crypt.py", line 24, in decrypt
    cipher = AES.new(settings.SITE_SETTINGS_KEY, AES.MODE_ECB)
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/home/siolag161/.virtualenvs/tendenci/local/lib/python2.7/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: AES key must be either 16, 24, or 32 bytes long
```

I think it's indeed an issue. I understand we have to change in the production code, but  we have to inform or enforce users to use a strong of length of either `16,24,32`?

**Comment by jennyq** [comment]
For the security purpose, both SECRET_KEY and SITE_SETTINGS_KEY need to be randomly-generated for each site so they don't use the default values. Maybe prompt for update instead of errors? Will fix it. Thanks!

**Comment by eschipul** [comment]
Yes, I definitely think you are correct both are correct.

And really, we weren't trying to play mind games with developers like that as that is a waste of everyone's time. You solved the puzzle, but why did I miss the commit that introduced an unnecessary puzzle? Well, actually I know why, we don't have enough outside developers (LIKE YOU!) committing to the code base and that has led our team and contractors to retreat to our private gilab server (a necessity for client sites, but not intended for core code). And I'm pushing hard to get all of that code out to github ASAP so you'll probably see some giant commits by the committers soon.

In the short term, i vote we make it as you did, static and 32 characters. While I could make that edit, I'd much rather give you credit if you don't mind doing a pull request so I can merge it in if you are willing. If you are too busy I get that and can do the update.

Long term in addition we need to push out some of the contents of our deployment scripts which randomize everything (every db has a different username and different password for example). But I'm not even going to ask the core team about that until we get Tendenci 6 stable as we set an April 21 deadline on Tendenci 4 several months ago (it was first written in ASP ... hey now, there was no php or Python back then).  In other words, about 100 sites have to go live on Tendenci 6 or move to a proprietary option based on Microsoft's EOL timelines. 

Re the key - I think the urgency is such that even if we have the same key for everyone and instructions to change it in README.MD that is better than the current error out. Then we can circle back and generate a stronger but consistent cipher. 

You tell me - Pull request and I'll commit it or just tell me to make the commit?

And THANK YOU! 

PS - Unit Tests - we're not quite there yet. Again - would love contributions. Tendenci 5/6 has been a race to recreate Tendenci 4 functionality which we worked on for 9 years. Just getting to baseline functionality for our current client base has been a challenge but we are finally getting much closer with Tendenci 6 and bootstrap3 themes....

**Comment by siolag161** [comment]
Yeah, don't mention it, I really appreciate the work you've done and the fact you've open sourced it.

Personally I do not mind much. Normally for my projects I have a heroku-like setup (I saw that you abandoned them) in which I have a `.env` file. Then I could write something like 

```bash
echo SITE_SETTINGS_KEY_ENV=`date | md5sum | head -c${1:-32} >> .env`
```
and then in the `local_settings.py` we have:

```python
import os
SECRET_KEY=os.environ.get('SECRET_KEY_ENV','your_unique_secret_key_Qoh222VG9pq8P9hOapH')
SITE_SETTINGS_KEY=os.environ.get('SITE_SETTINGS_KEY_ENV','0b425616d665d89fb6ee917b7122b5bf')
```
you know, for those who just want to try things out quickly. I'll think of a better solution if I have time.

**Comment by eschipul** [comment]
Were taking sites live on dockers these days and will hopefully get a docker-compose and an official docker out there soon. The .env file goes away in Tendenci 6 entirely as it was legacy. Check out the tendenci-project-template repo if you want to try the T6 branch. Thanks!
