### ISSUE TITLE
missing project_template

### ISSUE THREAD

**Issue by ipsec** [tendenci/tendenci#367]
tendenci==6.0.18

# create-tendenci-project 
Traceback (most recent call last):
  File "/var/www/site/venv/bin/create-tendenci-project", line 9, in <module>
    load_entry_point('tendenci==6.0.18', 'console_scripts', 'create-tendenci-project')()
  File "/var/www/site/venv/local/lib/python2.7/site-packages/tendenci/bin/create_tendenci_project.py", line 38, in create_project
    copy_tree(os.path.join(package_path, "project_template"), project_path)
  File "/usr/lib/python2.7/distutils/dir_util.py", line 128, in copy_tree
    "cannot copy tree '%s': not a directory" % src
distutils.errors.DistutilsFileError: cannot copy tree '/var/www/site/venv/local/lib/python2.7/site-packages/tendenci/project_template': not a directory

**Comment by ipsec** [comment]
django-admin.py startproject --template=https://github.com/tendenci/tendenci-project-template/zipball/master <name>

:)

**Comment by eschipul** [comment]
That tells me I need to get on the documentation soon. We've been putting it off a bit pending moving t6 to master. Thanks for posting the fix.
