### ISSUE TITLE
wsgi.py needs to be moved for tendency to start behind wigs

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#369]
```
root@tendenci:/srv/tendenci7_test_site# service tendenci-test start
root@tendenci:/srv/tendenci7_test_site# tail -n 20 /var/log/tendenci-test.error 
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
ImportError: No module named wsgi
Traceback (most recent call last):
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
ImportError: No module named wsgi
[2015-08-09 08:58:19 +0000] [2539] [INFO] Worker exiting (pid: 2539)
root@tendenci:/srv/tendenci7_test_site# cp conf/wsgi.py wsgi.py
root@tendenci:/srv/tendenci7_test_site# service tendenci-test start
root@tendenci:/srv/tendenci7_test_site# tail -n 20 /var/log/tendenci-test.error 
    worker.init_process()
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
ImportError: No module named wsgi
[2015-08-09 08:58:19 +0000] [2539] [INFO] Worker exiting (pid: 2539)
[2015-08-09 08:58:42 +0000] [2578] [INFO] Starting gunicorn 19.3.0
[2015-08-09 08:58:42 +0000] [2578] [INFO] Listening at: http://127.0.0.1:8000 (2578)
[2015-08-09 08:58:42 +0000] [2578] [INFO] Using worker: sync
[2015-08-09 08:58:42 +0000] [2583] [INFO] Booting worker with pid: 2583
[2015-08-09 08:58:42 +0000] [2584] [INFO] Booting worker with pid: 2584
[2015-08-09 08:58:42 +0000] [2587] [INFO] Booting worker with pid: 2587
[2015-08-09 08:58:43 +0000] [2590] [INFO] Booting worker with pid: 2590
```

This is the gunicorn configuration I'm using (fro the system unit file)
```
[Service]
WorkingDirectory=/srv/tendenci7_test_site
PIDFile=/run/tendenci-test.pid
Type=forking
KillMode=process
Restart=restart-always
ExecStart=/srv/venv_sage_test_site/bin/gunicorn        \
          --group root                                          \
          --user root                                           \
          --workers 4                                           \
          --bind=127.0.0.1:8000                                 \
          --pid=/run/tendenci-test.pid                 \
          --pythonpath=/srv/tendenci7_test_site           \
          --error-logfile=/var/log/tendenci-test.error \
          --daemon                                              \
          wsgi:application
```

**Comment by eschipul** [comment]
From an Ubuntu 14.04.2 vmware instance on my local. This is my gunicorn startup file, which varies slightly from the docs but you get the idea.

	root@ubuntu:/etc/init# cat tendenci.conf 

	description "Tendenci Upstart Script"
	start on runlevel [2345]
	stop on runlevel [06]
	respawn
	respawn limit 10 5
	script
	    cd /opt/webapps/tendenci_314159
	    exec gunicorn -w 2 -b 127.0.0.1:8000 conf.wsgi --max-requests 350
	end script

And this is my sites-enabled configuration:

	root@ubuntu:/etc/nginx/sites-enabled# cat tendenci_314159 

    server {
        listen 80;
        server_name localhost 192.168.184.128;

        charset   utf-8;
        keepalive_timeout  65;
        client_max_body_size  30M;
        root /opt/webapps/tendenci_314159;

        location /static/ {
            access_log off;
            expires 30d;
        }
     
        location /media/ {
            access_log off;
            expires 30d;
        }

        location ~ /themes/([a-zA-Z0-9\-\_]+)/media/ {
            access_log off;
        }

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://127.0.0.1:8000/;
        }
    }

1) Can you please attach your tendenci.conf file from /etc/init/  ? 

2) Can you please attach a "pip freeze" for your install (virtualenv or whatever the scope of virtual is)? This one I'm asking as I'm confused on the error message saying gunicorn isn't installed.

**Comment by goetzk** [comment]
On 9/08/2015 09:48, Ed Schipul wrote:
> From an Ubuntu 14.04.2 vmware instance on my local. This is my gunicorn
> startup file, which varies slightly from the docs but you get the idea.
> 
> |root@ubuntu:/etc/init# cat tendenci.conf description "Tendenci Upstart
> Script" start on runlevel [2345] stop on runlevel [06] respawn respawn
> limit 10 5 script cd /opt/webapps/tendenci_314159 exec gunicorn -w 2 -b
> 127.0.0.1:8000 conf.wsgi --max-requests 350 end script |
Hi Ed,
While on the plane I did some more digging and found this line is the
problem in my configuration.
I was using wsgi::application (as copied from someone elses example)
instead of conf.wsgi as you note here.

This issue can be closed and I've updated my files.
