### ISSUE TITLE
Can't view invoices

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#373]
Browsed to http://192.168.56.101/admin/memberships/membershipdefault/?o=3 as admin then took the following steps:
* renewed a member
* tried to view the invoice

This resulted in an attribute error.

```
AttributeError at /invoices/9/
'super' object has no attribute 'get_query_set'
Request Method:	GET
Request URL:	http://192.168.56.101/invoices/9/
Django Version:	1.8.3
Exception Type:	AttributeError
Exception Value:	
'super' object has no attribute 'get_query_set'
Exception Location:	/srv/venv_sage_test_site/local/lib/python2.7/site-packages/tendenci/apps/invoices/managers.py in all_invoices, line 54
Python Executable:	/srv/venv_sage_test_site/bin/python
Python Version:	2.7.9
Python Path:	
['/srv/tendenci7_test_site',
 '/srv/tendenci7_test_site',
 '/srv/venv_sage_test_site/bin',
 '/srv/venv_sage_test_site/lib/python2.7',
 '/srv/venv_sage_test_site/lib/python2.7/plat-x86_64-linux-gnu',
 '/srv/venv_sage_test_site/lib/python2.7/lib-tk',
 '/srv/venv_sage_test_site/lib/python2.7/lib-old',
 '/srv/venv_sage_test_site/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/srv/venv_sage_test_site/local/lib/python2.7/site-packages']
Server time:	Sun, 9 Aug 2015 09:18:44 +1000
```

I can include more backtrace but there are many pages of it.

**Comment by eschipul** [comment]
@goetzk - thank you for the details! Before jumping into specifics, and yes we need to update the docs and would welcome your help, but can you check two things for me please?

1) Did you install default data for npo_defaults? I've seen a few issues related to missing dependencies which means we need to fix the fixtures. But to get up and running for now it really needs default data:
https://github.com/tendenci/tendenci/blob/master/docs/source/installation/remote.txt#L101

    python manage.py load_base_defaults

2) Can you try upgrading to the latest branch?
> From the root of your site /var/www/tendenci/ or /opt/webapps/tendenci/ or similar:

    pip install -r requirements.txt --upgrade
    python deploy.py
    python manage.py clear_cache
    service tendenci restart

**Comment by goetzk** [comment]
According to my shell history I did not run load_base_defaults, only load_npo_defaults. If i need to run load_base_defaults I'll do that and see if it fixes my install.
```
  385  cd /srv/tendenci7_test_site/
  386  cd ..
  387  source venv_sage_test_site/bin/activate
  388  cd -
  389  python manage.py load_npo_defaults
  390  python manage.py createsuperuser
  391  python manage.py runserver
  392  python manage.py runserver 192.168.56.101:8000
```

At the moment I'm running tendenci 7.0.3
```
root@tendenci:~# source /srv/venv_sage_test_site/bin/activate
(venv_sage_test_site)root@tendenci:~# pip list |grep tenden
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
tendenci (7.0.3)
tendenci-case-studies (7.0.0)
tendenci-committees (7.0.0)
tendenci-donations (7.0.0)
tendenci-speakers (7.0.0)
tendenci-staff (7.0.0)
tendenci-studygroups (7.0.0)
tendenci-testimonials (7.0.0)
tendenci-videos (7.0.0)
```
Should I run the update block you have provided anyway?

**Comment by goetzk** [comment]
I have loaded the base defaults and encountered an error - i will leave the updates until i hear back from you on that point.
```
(venv_sage_test_site)root@tendenci:/srv/tendenci7_test_site# python manage.py load_base_defaults
[...]
updating files
npo_default_profiles_profile.json
Installed 20 object(s) from 1 fixture(s)
npo_default_forms.json
Installed 6 object(s) from 1 fixture(s)
npo_default_boxes.json
Installed 17 object(s) from 1 fixture(s)
npo_default_pages.json
Installed 8 object(s) from 1 fixture(s)
npo_default_navs.json
Installed 27 object(s) from 1 fixture(s)
npo_default_stories.json
Installed 11 object(s) from 1 fixture(s)
npo_default_videos.json
/srv/venv_sage_test_site/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py:225: UserWarning: No fixture named 'npo_default_videos' found.
  warnings.warn("No fixture named '%s' found." % fixture_name)

Installed 0 object(s) from 0 fixture(s)
(venv_sage_test_site)root@tendenci:/srv/tendenci7_test_site# 
````

**Comment by goetzk** [comment]
Hi @eschipul ,

I tried upgrading but had a few problems.

Firstly I had to comment out pylibmc==1.2.2 in requirements/prod.txt due to a compilation error I couldn't figure out.
```
Building wheels for collected packages: pylibmc
  Running setup.py bdist_wheel for pylibmc
  Complete output from command /srv/venv_sage_test_site/bin/python -c "import setuptools;__file__='/tmp/pip-build-v_PTw9/pylibmc/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpQunhikpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pylibmc
  copying pylibmc/client.py -> build/lib.linux-x86_64-2.7/pylibmc
  copying pylibmc/__init__.py -> build/lib.linux-x86_64-2.7/pylibmc
  copying pylibmc/pools.py -> build/lib.linux-x86_64-2.7/pylibmc
  copying pylibmc/__main__.py -> build/lib.linux-x86_64-2.7/pylibmc
  copying pylibmc/test.py -> build/lib.linux-x86_64-2.7/pylibmc
  copying pylibmc/consts.py -> build/lib.linux-x86_64-2.7/pylibmc
  running build_ext
  building '_pylibmc' extension
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE_ZLIB -I/usr/include/python2.7 -c _pylibmcmodule.c -o build/temp.linux-x86_64-2.7/_pylibmcmodule.o -fno-strict-aliasing
  _pylibmcmodule.c: In function ‘PylibMC_Client_delete’:
  _pylibmcmodule.c:1001:15: warning: variable ‘retval’ set but not used [-Wunused-but-set-variable]
       PyObject *retval;
                 ^
  _pylibmcmodule.c: In function ‘_get_lead’:
  _pylibmcmodule.c:1892:13: warning: assignment discards ‘const’ qualifier from pointer target type
           svr = memcached_server_by_key(mc, key, len, &rc);
               ^
  _pylibmcmodule.c:1895:31: error: dereferencing pointer to incomplete type
                              svr->hostname, svr->port);
                                 ^
  _pylibmcmodule.c:1895:46: error: dereferencing pointer to incomplete type
                              svr->hostname, svr->port);
                                                ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pylibmc
Failed to build pylibmc
Installing collected packages: pylibmc, django-pylibmc-sasl, raven, tendenci, tendenci-donations, tendenci-case-studies, tendenci-committees, tendenci-speakers, tendenci-staff, tendenci-studygroups, tendenci-videos, tendenci-testimonials, django-sql-explorer, django-avatar, setuptools
  Running setup.py install for pylibmc
    Complete output from command /srv/venv_sage_test_site/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-v_PTw9/pylibmc/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-YW1kyx-record/install-record.txt --single-version-externally-managed --compile --install-headers /srv/venv_sage_test_site/include/site/python2.7/pylibmc:
    running install
    running build
    running build_py
    running build_ext
    building '_pylibmc' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE_ZLIB -I/usr/include/python2.7 -c _pylibmcmodule.c -o build/temp.linux-x86_64-2.7/_pylibmcmodule.o -fno-strict-aliasing
    _pylibmcmodule.c: In function ‘PylibMC_Client_delete’:
    _pylibmcmodule.c:1001:15: warning: variable ‘retval’ set but not used [-Wunused-but-set-variable]
         PyObject *retval;
                   ^
    _pylibmcmodule.c: In function ‘_get_lead’:
    _pylibmcmodule.c:1892:13: warning: assignment discards ‘const’ qualifier from pointer target type
             svr = memcached_server_by_key(mc, key, len, &rc);
                 ^
    _pylibmcmodule.c:1895:31: error: dereferencing pointer to incomplete type
                                svr->hostname, svr->port);
                                   ^
    _pylibmcmodule.c:1895:46: error: dereferencing pointer to incomplete type
                                svr->hostname, svr->port);
                                                  ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/srv/venv_sage_test_site/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-v_PTw9/pylibmc/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-YW1kyx-record/install-record.txt --single-version-externally-managed --compile --install-headers /srv/venv_sage_test_site/include/site/python2.7/pylibmc" failed with error code 1 in /tmp/pip-build-v_PTw9/pylibmc
```

After that I reran the upgrade command which finished successfully but when i try and run deploy I have the following error.

```
(venv_sage_test_site)root@tendenci:/srv/tendenci7_test_site# python deploy.py
/srv/venv_sage_test_site/local/lib/python2.7/site-packages/captcha/models.py:36: RemovedInDjango19Warning: Model class captcha.models.CaptchaStore doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CaptchaStore(models.Model):

/srv/venv_sage_test_site/local/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

/srv/venv_sage_test_site/local/lib/python2.7/site-packages/tendenci/apps/events/forms.py:16: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

/srv/venv_sage_test_site/local/lib/python2.7/site-packages/form_utils/forms.py:12: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
  from django.forms.util import flatatt, ErrorDict

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 176, in build_graph
    self.load_disk()
  File "/srv/venv_sage_test_site/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 111, in load_disk
    "Migration %s in app %s has no Migration class" % (migration_name, app_config.label)
django.db.migrations.loader.BadMigrationError: Migration signals in app user_groups has no Migration class
Traceback (most recent call last):
  File "deploy.py", line 3, in <module>
    subprocess.check_call(['python', 'manage.py',  'migrate', '--noinput'])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'migrate', '--noinput']' returned non-zero exit status 1
```

**Comment by eschipul** [comment]
@goetzk - I hit the same error doing a fresh install. Then got impatient and not sure what I did to get past it. I did see Jenny already merged your pull. Thank you!

For the defaults (base/npo) - it's either/or. I rebuilt using base defaults this time and will let you know how it goes. Already hit an obstacle on directories pricing which I added an issue for.

As for the update, yes, @jennyq just added a script that is brilliant and creates the fixtures without the out-of-memory errors. Make a backup of course, or snapshot of vmware which is my preferred method, and update to the latest. If you haven't done too much content work you might want to create a new db entirely at least for testing.

Last version bump commit.
https://github.com/tendenci/tendenci/commit/401a63082f41b69792df830a66162ed1b8bad0ac

Tendenci 7 isn't a huge change on the front end, but it is a giant change on the back end with the move to django 1.8 and we are still working through this. And we appreciate you being a part of the community!

**Comment by goetzk** [comment]
Something in the last set of commits must have fixed the upgrade problem - migration appears to be working now.

For search ability i'll include this last block of text.

```
pip install -r requirements/dev.txt --upgrade
Collecting https://github.com/tendenci/tendenci/archive/tendenci7.zip (from -r requirements/common.txt (line 1))
  Downloading https://github.com/tendenci/tendenci/archive/tendenci7.zip (18.7MB)
    100% |████████████████████████████████| 18.7MB 18kB/s 
[downloads all outstanding updates]
```
After that I tried to run the migrations using the commands you provided at the start

```
()root@tendenci:/srv/tendenci7_sage_site# python deploy.py && python manage.py clear_cache 
CommandError: Conflicting migrations detected (0002_auto_20150809_0254, 0002_auto_20150827_1627 in speakers; 0003_auto_20150809_0254, 0003_registrant_salutation in events; 0002_auto_20150809_0254, 0002_auto_20150827_1627 in videos).
To fix them run 'python manage.py makemigrations --merge'
Traceback (most recent call last):
  File "deploy.py", line 3, in <module>
    subprocess.check_call(['python', 'manage.py',  'migrate', '--noinput'])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'manage.py', 'migrate', '--noinput']' returned non-zero exit status 1
```

went for brute force and ignorance to merge them
```
()root@tendenci:/srv/tendenci7_sage_site# python manage.py makemigrations --merge
Merging speakers
  Branch 0002_auto_20150809_0254
    - Alter field ordering on speaker
  Branch 0002_auto_20150827_1627
    - Alter field ordering on speaker

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Do you want to merge these migration branches? [y/N] y

Created new merge migration /srv/venv_sage_test_site/local/lib/python2.7/site-packages/speakers/migrations/0003_merge.py
Merging events
  Branch 0003_auto_20150809_0254
    - Alter field timezone on event
  Branch 0003_registrant_salutation
    - Add field salutation to registrant

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Do you want to merge these migration branches? [y/N] y

Created new merge migration /srv/venv_sage_test_site/local/lib/python2.7/site-packages/tendenci/apps/events/migrations/0004_merge.py
Merging videos
  Branch 0002_auto_20150809_0254
    - Change Meta options on video
  Branch 0002_auto_20150827_1627
    - Change Meta options on video

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Do you want to merge these migration branches? [y/N] y

Created new merge migration /srv/venv_sage_test_site/local/lib/python2.7/site-packages/videos/migrations/0003_merge.py
```

Now I'm able to run the migration.
```
()root@tendenci:/srv/tendenci7_sage_site# python deploy.py && python manage.py clear_cache 
Operations to perform:
[...]
enabled (testimonials)  - updated.
All done.
Installed 516 object(s) from 6 fixture(s)
```

Doing this I noticed i wasn't using requirements.txt so opened #404 and re ran using requirements.txt - that seems to be what makes it error out. I'll investigate further and potentially raise a new ticket for that problem.
