### ISSUE TITLE
issue with url lib dependency

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#403]
Following the install docs when i run djang-admin i get the following error

```
/usr/bin/pip run on Sat Aug 29 17:56:24 2015
Downloading/unpacking https://github.com/tendenci/tendenci/archive/tendenci7.zip (from -r requirements/common.txt (line 1))
  Downloading from URL https://github.com/tendenci/tendenci/archive/tendenci7.zip
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 572, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 433, in _download_url
    for chunk in resp_read(4096):
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 421, in resp_read
    chunk_size, decode_content=False):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 851, in _raise_ssl_error
    raise ZeroReturnError()
ZeroReturnError
```

The fix is to upgrade urllib, in my case from: 1.9.1 to: 1.11.

```
Downloading/unpacking urllib3 from https://pypi.python.org/packages/py2.py3/u/urllib3/urllib3-1.11-py2.py3-none-any.whl#md5=bfe41df0dbc47880ba15960be721a08b
  Downloading urllib3-1.11-py2.py3-none-any.whl (84kB): 84kB downloaded
Installing collected packages: urllib3
  Found existing installation: urllib3 1.9.1
    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed urllib3
Cleaning up...
```

Not sure if this is worth documenting or not but i thought I'd mention it in case.

**Comment by goetzk** [comment]
Interestingly I didn't encounter this last week; it may have been a transient issue but further testing will confirm that.

**Comment by jennyq** [comment]
@goetzk, it doesn't seem to be an issue now. Closing it.. Please reopen it if the issue persists for you.
