### ISSUE TITLE
load_base_defaults broken in 7.1

### ISSUE THREAD

**Issue by poelzi** [tendenci/tendenci#464]
When I ran load_base_defaults on a freshly install 7.1.25 the fixtures throw errors:

```
(virtenv)tendenci@web-ubuntu-1404:~$ python manage.py load_ngo_defaults
/srv/sg_web/virtenv/local/lib/python2.7/site-packages/captcha/models.py:30: RemovedInDjango19Warning: Model class captcha.models.CaptchaStore doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CaptchaStore(models.Model):

/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

Unknown command: 'load_ngo_defaults'
Type 'manage.py help' for usage.
(virtenv)tendenci@web-ubuntu-1404:~$ python manage.py load_ngo_default
/srv/sg_web/virtenv/local/lib/python2.7/site-packages/captcha/models.py:30: RemovedInDjango19Warning: Model class captcha.models.CaptchaStore doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CaptchaStore(models.Model):

/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

Unknown command: 'load_ngo_default'
Type 'manage.py help' for usage.
(virtenv)tendenci@web-ubuntu-1404:~$ python manage.py load_ngo_defaults
/srv/sg_web/virtenv/local/lib/python2.7/site-packages/captcha/models.py:30: RemovedInDjango19Warning: Model class captcha.models.CaptchaStore doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CaptchaStore(models.Model):

/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

Unknown command: 'load_ngo_defaults'
Type 'manage.py help' for usage.
(virtenv)tendenci@web-ubuntu-1404:~$ python manage.py load_base_defaults
/srv/sg_web/virtenv/local/lib/python2.7/site-packages/captcha/models.py:30: RemovedInDjango19Warning: Model class captcha.models.CaptchaStore doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class CaptchaStore(models.Model):

/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

/srv/sg_web/media/directories/1/directory-img-1.jpg

[...]

029bc_medium_640-ae2be_small.jpg
npo_default_auth_user.json
Installed 20 object(s) from 1 fixture(s)
npo_default_entities.json
Installed 10 object(s) from 1 fixture(s)
npo_default_user_groups.json
Installed 26 object(s) from 1 fixture(s)
npo_default_files.json
Installed 36 object(s) from 1 fixture(s)
paymentmethod.json
Installed 3 object(s) from 1 fixture(s)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/tendenci/apps/base/management/commands/load_base_defaults.py", line 36, in handle
    self.call_loaddata(reset_nav)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/tendenci/apps/base/management/commands/load_base_defaults.py", line 141, in call_loaddata
    call_command('load_sqlexplorer_defaults')
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/tendenci/apps/base/management/commands/load_sqlexplorer_defaults.py", line 77, in handle
    query.save()
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/sg_web/virtenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "snapshot" of relation "explorer_query" does not exist
LINE 1: ...eated_by_user_id", "created_at", "last_run_date", "snapshot"...
                                                             ^
```

I guess it tries to fetch the fixtures that are for tendenci 5.x and the model changed.

**Comment by poelzi** [comment]
my bad. python deploy.py needs to be run first.
