### ISSUE TITLE
errors during migrate_initials

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#510]
I seem to be having a problem while running migrate_initials.sh, I wonder if a new dependency has been added.

```
ubuntu@tendenci-web:/srv/tendenci/website$ pip list |grep tenden
tendenci (7.2.34)
ubuntu@tendenci-web:/srv/tendenci/website$ pip list |grep Django
Django (1.8.14)
ubuntu@tendenci-web:/srv/tendenci/website$ 
```

The error relates to missing GEOS support

```
ubuntu@tendenci-web:/srv/tendenci/website$ bash migrate_initials.sh 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/haystack/__init__.py", line 57, in <module>
    signal_processor_class = loading.import_class(signal_processor_path)
  File "/usr/local/lib/python2.7/dist-packages/haystack/utils/loading.py", line 32, in import_class
    module_itself = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/search/signals.py", line 6, in <module>
    from tendenci.apps.search.models import UnindexedItem
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/search/models.py", line 5, in <module>
    class UnindexedItem(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 139, in __new__
    new_class.add_to_class('_meta', Options(meta, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 250, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python2.7/dist-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 241, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 112, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/db/backends/postgis/base.py", line 8, in <module>
    from .features import DatabaseFeatures
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/db/backends/postgis/features.py", line 1, in <module>
    from django.contrib.gis.db.backends.base.features import BaseSpatialFeatures
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/db/backends/base/features.py", line 3, in <module>
    from django.contrib.gis.db.models import aggregates
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/gis/db/models/__init__.py", line 12, in <module>
    "See also https://docs.djangoproject.com/en/%s/ref/contrib/gis/install/geolibs/" % get_docs_version())
django.core.exceptions.ImproperlyConfigured: GEOS is required and has not been detected. Are you sure it is installed? See also https://docs.djangoproject.com/en/1.8/ref/contrib/gis/install/geolibs/
```

running
  sudo apt install python-gdal
has  mean the error no longer occurs but the correct fix depends on if gdal support is desired or not.

**Comment by jennyq** [comment]
@goetzk does the error occur on Ubuntu 14.04 or 16.04?

**Comment by goetzk** [comment]
@jennyq Sorry I thought I included that but seemingly not - 14.04.5.

**Comment by jennyq** [comment]
I just tested on `Ubuntu 14.04.5 LTS` but couldn't replicate the issue. When I checked the list of the installed packages, `python-gdal` was not in there. I did see `libgdal1h` on the list though.

**Comment by goetzk** [comment]
No, you are correct. I try and make sure I am catching old tickets but this one appears to have slipped past me.
kk
