### ISSUE TITLE
Bug in DB creation on latest version

### ISSUE THREAD

**Issue by jennyq** [tendenci/tendenci#536]
This is the issue 4EJeffe reported on tendenci forum https://www.tendenci.com/forums/c/support/support/bug-in-db-creation-on-latest-version/.

> So after further investigation it appears there is a bug in the most up to date version of Tendenci when creating the DB on a new install. We were FINALLY able to get the install done by installing under an old version.
> 
> Here are the grotty details:
> 
> Applying files.0001_initial...Traceback (most recent call last): File "manage.py", line 10, in execute_from_command_line(sys.argv) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/init.py", line 354, in execute_from_command_line utility.execute() File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/init.py", line 346, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv self.execute(*args, cmd_options) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute output = self.handle(*args, options) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration state = migration.apply(state, schema_editor) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply operation.database_forwards(self.app_label, schema_editor, old_state, project_state) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards field, File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/schema.py", line 94, in add_field super(PostGISSchemaEditor, self).add_field(model, field) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/schema.py", line 18, in add_field super(DatabaseSchemaEditor, self).add_field(model, field) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 384, in add_field definition, params = self.column_sql(model, field, include_default=True) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/schema.py", line 25, in column_sql return super(PostGISSchemaEditor, self).column_sql(model, field, include_default) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 146, in column_sql default_value = self.effective_default(field) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 198, in effective_default default = field.get_default() File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1947, in get_default field_default = super(ForeignKey, self).get_default() File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/models/fields/init.py", line 794, in get_default return self.default() File "/srv/tendenci/venv/local/lib/python2.7/site-packages/tendenci/apps/user_groups/utils.py", line 39, in get_default_group id=Group.objects.get_initial_group_id()) or [None])[0] File "/srv/tendenci/venv/local/lib/python2.7/site-packages/tendenci/apps/user_groups/managers.py", line 61, in get_initial_group_id group = self.get_or_create_default() File "/srv/tendenci/venv/local/lib/python2.7/site-packages/tendenci/apps/user_groups/managers.py", line 26, in get_or_create_default group = self.first() File "/srv/tendenci/venv/local/lib/python2.7/site-packages/tendenci/apps/user_groups/managers.py", line 19, in first [group] = groups[:1] or [None] File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 170, in nonzero return type(self).bool(self) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 166, in bool self._fetch_all() File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all self._result_cache = list(self.iterator()) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator results = compiler.execute_sql() File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql cursor.execute(sql, params) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute return super(CursorDebugWrapper, self).execute(sql, params) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute return self.cursor.execute(sql, params) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in exit six.reraise(dj_exc_type, dj_exc_value, traceback) File "/srv/tendenci/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute return self.cursor.execute(sql, params) django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block
> - See more at: https://www.tendenci.com/forums/c/support/support/bug-in-db-creation-on-latest-version/#sthash.7PCfiWYT.dpuf

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/1e3dd654720191623edc20e2440d3c4d2e1be3ee. It appears that the latest version of Django 1.8.x doesn't take a model instance as the default value for a foreign key on migration anymore.
