### ISSUE TITLE
upload photo error:IOError: broken data stream when reading image file

### ISSUE THREAD

**Issue by 110273315** [tendenci/tendenci#553]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/smartac/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/smartac/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/smartac/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/smartac/tendenci/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/smartac/tendenci/venv/local/lib/python2.7/site-packages/tendenci/apps/photos/management/commands/precache_photo.py", line 19, in handle
    cache_photo_size(**cache_kwargs)
  File "/smartac/tendenci/venv/local/lib/python2.7/site-packages/tendenci/apps/photos/utils/caching.py", line 43, in cache_photo_size
    image = get_image(photo.image, size, PHOTO_PRE_KEY, crop=crop, quality=quality, unique_key=str(photo.pk), constrain=constrain)
  File "/smartac/tendenci/venv/local/lib/python2.7/site-packages/tendenci/apps/files/utils.py", line 50, in get_image
    binary = build_image(file, size, pre_key, **kwargs)
  File "/smartac/tendenci/venv/local/lib/python2.7/site-packages/tendenci/apps/files/utils.py", line 96, in build_image
    image = image.resize(size, Image.ANTIALIAS)  # resize image
  File "/smartac/tendenci/venv/local/lib/python2.7/site-packages/PIL/Image.py", line 1538, in resize
    self.load()
  File "/smartac/tendenci/venv/local/lib/python2.7/site-packages/PIL/ImageFile.py", line 235, in load
    raise_ioerror(e)
  File "/smartac/tendenci/venv/local/lib/python2.7/site-packages/PIL/ImageFile.py", line 59, in raise_ioerror
    raise IOError(message + " when reading image file")
IOError: broken data stream when reading image file

**Comment by jennyq** [comment]
@110273315, Although I cannot replicate the issue, I think it might have something to do with the old version of Pillow and/or a malformed image.  Please try again with the latest version of tendenci and let us know the result. Thanks!

**Comment by eschipul** [comment]
Closing issue from inactivity. Feel free to open again and provide more data such as a link to gist to replicate the steps, size of the image, nginx log files, nginx mime type listing, etc....
