### ISSUE TITLE
Step 5 Fake initials

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#619]
On step 5 says to do python manage.py fake_initials, and I get this:

Operations to perform:
  Target specific migration: 0001_initial, from contenttypes
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... FAKED
Operations to perform:
  Apply all migrations: contenttypes
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0002_remove_content_type_name... OK
The following content types are stale and need to be deleted:

    memberships | app
    memberships | appfieldentry
    memberships | membership
    memberships | noticelogrecord
    memberships | appentry
    memberships | appfield

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: 

Is it going to delete all the members that the old website had?

**Comment by jennyq** [comment]
What tendenci version is your old site on? It won't delete all the members if the old site is on the latest version of T5.

**Comment by dco5** [comment]
The version I am upgrading from is 5.2.4

**Comment by jennyq** [comment]
Then it should be safe to type "yes". The memberships has already been ported to the new database tables in that version.

**Comment by dco5** [comment]
I type yes and got this error:
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/tendenci/apps/base/management/commands/fake_initials.py", line 22, in handle
    call_command('migrate', 'contenttypes', '0002', '--fake')
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 226, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/core/management/sql.py", line 280, in emit_post_migrate_signal
    using=db)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/contrib/contenttypes/management.py", line 81, in update_contenttypes
    ct.delete()
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/db/models/base.py", line 895, in delete
    collector.collect([self])
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 228, in collect
    elif sub_objs:
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jlossada/.envs/hapl7/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column recurring_payments_recurringpayment.platform does not exist
LINE 1: ...d", "recurring_payments_recurringpayment"."guid", "recurring...
`

**Comment by dco5** [comment]
I manually added the column platform to the table recurring_payments_recurringpayment it performe the migrations, I am hoping that was the solution.

**Comment by dco5** [comment]
I had to manually removed it again later when so that python manage.py migrate could run correctly.

**Comment by dco5** [comment]
now after the migrations are done I am getting:
Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

**Comment by jennyq** [comment]
The issue regarding prompt to run 'manage.py makemigrations' has been fixed in the T11. 
https://github.com/tendenci/tendenci/commit/82d81f57ff804be7124a04ff036224e431c90657

Please note that the 'manage.py makemigrations' command will create new migrations. So do not run it even if it prompts you to. Otherwise, it would mess up the future migrations for your site as the new migrations generated do not exist in the core.
