### ISSUE TITLE
Issues setting site up on Ubuntu 16.04 since Django 2.0 was released.

### ISSUE THREAD

**Issue by hammygoonan** [tendenci/tendenci#629]
It looks like `dj-pagination-2.3.0` uses some of the Django 2.0 library.

Here's the output from my command line:

```
pip install -r requirements/dev.txt
Collecting tendenci<8,>=7 (from -r requirements/tendenci.txt (line 2))
  Using cached tendenci-7.4.1.tar.gz
Collecting Django<1.9,>=1.8 (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached Django-1.8.18-py2.py3-none-any.whl
Collecting django-formtools>=1.0 (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached django_formtools-2.1-py2.py3-none-any.whl
Collecting pisa (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached pisa-3.0.33.tar.gz
Collecting Reportlab==3.3.0 (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached reportlab-3.3.0.tar.gz
Collecting html5lib==0.9999999 (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached html5lib-0.9999999.tar.gz
Collecting Pillow==4.2.1 (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached Pillow-4.2.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting anyjson>=0.2.4 (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached anyjson-0.3.3.tar.gz
Collecting django-authority>=0.4 (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached django-authority-0.11.tar.gz
Collecting django-countries==3.4.1 (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached django_countries-3.4.1-py2.py3-none-any.whl
Collecting django-form-utils>=0.1.8 (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached django-form-utils-1.0.3.tar.gz
Collecting django-localflavor==1.4.1 (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached django-localflavor-1.4.1.tar.gz
Collecting dj-pagination>=2.2.0 (from tendenci<8,>=7->-r requirements/tendenci.txt (line 2))
  Using cached dj-pagination-2.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-YWGxpU/dj-pagination/setup.py", line 87, in <module>
        include_package_data=True,
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 455, in fetch_build_eggs
        replace_conflicting=True,
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 866, in resolve
        replace_conflicting=replace_conflicting
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1146, in best_match
        return self.obtain(req, installer)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1158, in obtain
        return installer(requirement)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 882, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1136, in run_setup
        run_setup(setup_script, args)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/srv/tendenci/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-sV0BwV/Django-2.0/setup.py", line 32, in <module>

      File "/tmp/easy_install-sV0BwV/Django-2.0/django/__init__.py", line 1, in <module>
      File "/tmp/easy_install-sV0BwV/Django-2.0/django/utils/version.py", line 61, in <module>
    AttributeError: 'module' object has no attribute 'lru_cache'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-YWGxpU/dj-pagination/
```

Thanks for the awesome project!

**Comment by jennyq** [comment]
@hammygoonan, thank you for pointing out the issue! It looks like Django 1.8.18 was not installed when the `dj-pagination` was installed for some reason. Try to run `pip install Django==1.8.18`, then the command `pip install -r requirements/dev.txt` to see if the issue is gone. I couldn't replicate the issue in my vmware.

**Comment by hammygoonan** [comment]
Thanks @jennyq that worked. I've make a pull request to update the installation instructions.
