### ISSUE TITLE
'NoneType' object has no attribute 'get_donation_amount'

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#641]
Hi,
We started seeing the error below around the time I upgraded to Tendenci 7.3
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/tendenci/website/itpa/views.py", line 131, in activate_account
    membership_type=membership.membership_type,
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/memberships/models.py", line 2382, in send_notice
    'subject': notice.get_subject(membership=membership),
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/memberships/models.py", line 2270, in get_subject
    context = self.get_default_context(membership)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/memberships/models.py", line 2251, in get_default_context
    'donation_amount': inv.get_donation_amount(),
AttributeError: 'NoneType' object has no attribute 'get_donation_amount'
```

I've upgraded to 7.4 and we're still seeing it.

I'm happy to do some in place debugging if needed.

**Comment by jennyq** [comment]
Thanks @goetzk ! It's been fixed. https://github.com/tendenci/tendenci/commit/61d629b8e6e81f172ee27d3db2b2928b446f7607

**Comment by goetzk** [comment]
Great thanks!

I will try and update our system soon.

On 14 February 2018 3:37:21 am AEDT, Jenny Qian <notifications@github.com> wrote:
>Thanks @goetzk ! It's been fixed.
>https://github.com/tendenci/tendenci/commit/61d629b8e6e81f172ee27d3db2b2928b446f7607
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tendenci/tendenci/issues/641#issuecomment-365324060

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
