### ISSUE TITLE
Troubles in migrating on AWS EC2 micro/medium/large instances with Ubuntu 16.04

### ISSUE THREAD

**Issue by surajprasad** [tendenci/tendenci#668]
This has taken up 2 days already and it seems the error / bug is very unique and may not have anything to do with dependencies etc. 
So, setting up and installing the dependencies on the AWS EC2 is not a challenge, and takes up only about an hour. After virtualenv and pip installation, "pip install tendenci" still points to the old requirements file where psycopg2 is an older version and so it fails. 
then, as instructed by @jennyq I try installing it from the master branch and get the project template. 
It all seems fine so far. 

Postgres installation is also straight forward and the extension creation also goes smoothly. 
The problem happens with you proceed with migration. 

When project template is pulled down, it brings the migrations too and therefore we have 0001, 0002, 0003 and so on migrations in some apps. 
python manage.py migrate then fails abruptly at various apps with something similar to the below;

Rendering model states... DONE
  Applying articles.0002_auto_20180321_0229...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/schema.py", line 94, in add_field
    super(PostGISSchemaEditor, self).add_field(model, field)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 385, in add_field
    definition, params = self.column_sql(model, field, include_default=True)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/schema.py", line 25, in column_sql
    return super(PostGISSchemaEditor, self).column_sql(model, field, include_default)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 142, in column_sql
    default_value = self.effective_default(field)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 194, in effective_default
    default = field.get_default()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1929, in get_default
    field_default = super(ForeignKey, self).get_default()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 794, in get_default
    return self.default()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/tendenci/apps/user_groups/utils.py", line 39, in get_default_group
    return Group.objects.get_initial_group_id()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/tendenci/apps/user_groups/managers.py", line 61, in get_initial_group_id
    group = self.get_or_create_default()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/tendenci/apps/user_groups/managers.py", line 26, in get_or_create_default
    group = self.first()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/tendenci/apps/user_groups/managers.py", line 19, in first
    [group] = groups[:1] or [None]
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block

@jennyq Thanks for patching the fix for the articles. 
Then when I go back to running it, another app fails, so I decided to drop the DB and migrate on a clean DB, also as suggested in one of the other forums, I also delete all previous migrations using 
`find . -path "*/migrations/*.py" -not -name "__init__.py" -delete`

Then `python manage.py showmigrations` reports as expected,
`accountings
 (no migrations)
admin
 (no migrations)
announcements
 (no migrations)
articles
 (no migrations)`
.....

So I `makemigrations` again and try to run `migrate`
This time it fails at another app 'files'
`Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying accountings.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying entities.0001_initial... OK
  Applying announcements.0001_initial... OK
  Applying user_groups.0001_initial... OK
  Applying meta.0001_initial... OK
  Applying articles.0001_initial... OK
  Applying base.0001_initial... OK
  Applying boxes.0001_initial... OK
  Applying invoices.0001_initial... OK
  Applying payments.0001_initial... OK
  Applying forms.0001_initial... OK
  Applying campaign_monitor.0001_initial... OK
  Applying captcha.0001_initial... OK
  Applying careers.0001_initial... OK
  Applying files.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/tmp/pip-build-iBRBK_/Django/django/db/migrations/executor.py", line 110, in migrate
  File "/tmp/pip-build-iBRBK_/Django/django/db/migrations/executor.py", line 148, in apply_migration
  File "/tmp/pip-build-iBRBK_/Django/django/db/migrations/migration.py", line 115, in apply
  File "/tmp/pip-build-iBRBK_/Django/django/db/migrations/operations/fields.py", line 62, in database_forwards
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/schema.py", line 94, in add_field
    super(PostGISSchemaEditor, self).add_field(model, field)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/schema.py", line 18, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 384, in add_field
    definition, params = self.column_sql(model, field, include_default=True)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/schema.py", line 25, in column_sql
    return super(PostGISSchemaEditor, self).column_sql(model, field, include_default)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 146, in column_sql
    default_value = self.effective_default(field)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 198, in effective_default
    default = field.get_default()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1947, in get_default
    field_default = super(ForeignKey, self).get_default()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 794, in get_default
    return self.default()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/tendenci/apps/user_groups/utils.py", line 39, in get_default_group
    return Group.objects.get_initial_group_id()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/tendenci/apps/user_groups/managers.py", line 61, in get_initial_group_id
    group = self.get_or_create_default()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/tendenci/apps/user_groups/managers.py", line 26, in get_or_create_default
    group = self.first()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/tendenci/apps/user_groups/managers.py", line 19, in first
    [group] = groups[:1] or [None]
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block
`
I have tried various versions of this, several resets of migrations, and fresh database instances, but each time something fails. 

As far as I suspect it is something to do with tendenci migrations / django migrations of the particular django version. Hope the community can help figure this out. I will post a solution as soon as I can make complete sense of this. 

P.S: running migrations is not possible on ec2 micro instance or medium instance, it gets stuck for a long time and any other request from the shell is denied. Seems like tendenci requires a lot of memory for running migrations, is it also that heavy in the runtime? Will I end up having massive bills from Amazon?

Best.

**Comment by PaulSD** [comment]
It looks like Django is swallowing the real error and masking it behind a transaction error, so the above messages aren't terribly helpful.

However, if I'm reading this correctly, it seems like django is basically failing when running `SELECT * FROM "user_groups_group" WHERE ("user_groups_group"."status" = True AND "user_groups_group"."status" = False AND "user_groups_group"."status_detail" = active) ORDER BY "user_groups_group"."id" ASC LIMIT 1;`
Since the `user_groups` migration has already run, this shouldn't fail, but the error message above is suggesting that it is failing.
What happens if you connect directly to postgres and run that query?

On my system, each gunicorn worker uses 150-200MB of RAM, and running migrations uses about 250MB of RAM.  I haven't had any trouble running Tendenci in a VM with 2GB of RAM.  It sounds to me like something is broken on your system and is causing deeply nested recursion somewhere unexpected.

**Comment by jennyq** [comment]
Hi @surajprasad, 

Please **never** ever run `makemigrations` and do **not** delete migrations in the code when you installing tendenci. 

Please try again with a fresh database. What errors are you getting when you run these commands?

    pip install https://github.com/tendenci/tendenci/archive/master.zip --upgrade
    python manage.py migrate
    python deploy.py

**Comment by surajprasad** [comment]
@jennyq I ran your suggestions, the migrate fails with the following;
`/home/ubuntu/lightcube/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/tmp/pip-build-iBRBK_/Django/django/db/migrations/executor.py", line 19, in __init__
  File "/tmp/pip-build-iBRBK_/Django/django/db/migrations/loader.py", line 47, in __init__
  File "/tmp/pip-build-iBRBK_/Django/django/db/migrations/loader.py", line 321, in build_graph
  File "/tmp/pip-build-iBRBK_/Django/django/db/migrations/loader.py", line 291, in _reraise_missing_dependency
django.db.migrations.graph.NodeNotFoundError: Migration contributions.0001_initial dependencies reference nonexistent parent node (u'contenttypes', u'0002_remove_content_type_name')`

This is the second time I have seen the contenttypes related failure. Previously, it said that the 'please make sure contenttypes are migrated first before individual app migrations'

**Comment by jennyq** [comment]
@surajprasad, not sure if you have changed it back -  set `AUTOCOMMIT` to `True` if you have set it to `False` previously for the debug purpose.

**Comment by surajprasad** [comment]
@jennyq It is set to True. No effect.

**Comment by jennyq** [comment]
What is the version of django in your environment?

    pip freeze | grep Django

**Comment by surajprasad** [comment]
Its 1.8.19

**Comment by jennyq** [comment]
what's the result of this command?

    python manage.py migrate -l

**Comment by surajprasad** [comment]
So, I think I dozed off last night and couldn't respond. 
@jennyq This morning I ran the command, `python manage.py migrate -l`and I received the following;
`File "/home/ubuntu/lightcube/local/lib/python2.7/site-packages/django/core/management/commands/showmigrations.py", line 44, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/tmp/pip-build-iBRBK_/Django/django/db/migrations/loader.py", line 47, in __init__
  File "/tmp/pip-build-iBRBK_/Django/django/db/migrations/loader.py", line 321, in build_graph
  File "/tmp/pip-build-iBRBK_/Django/django/db/migrations/loader.py", line 291, in _reraise_missing_dependency
django.db.migrations.graph.NodeNotFoundError: Migration contributions.0001_initial dependencies reference nonexistent parent node (u'contenttypes', u'0002_remove_content_type_name')
`
So out of frustration, I decided the delete everything and start fresh. Dropped the existing database, and created fresh along with deleting the entire virtualenv and all that was there in the 'pip' cache too. 

Then I ran the install again and ran 
`pip install https://github.com/tendenci/tendenci/archive/master.zip --upgrade
django-admin.py startproject --template=https://github.com/tendenci/tendenci-project-template/zipball/master <project_name>
python manage.py migrate
python deploy.py`

Adding the database credentials etc, it took a long time after starting to deploy and finally, it ran all migrations, completely.

Finally, I have a running setup on the AWS that I can access from the public IP. 
Will proceed with the configuration now and share the url when it is all setup. 

Thank you for all the help people, I think it was something, somewhere wrong with the setup, not exactly sure where. 

PS: I am going to downgrade the EC2 memory requirements and see what is the most economical way to run tendenci. 

Best.

**Comment by jennyq** [comment]
Glad you've made it work!

**Comment by BenSturmfels** [comment]
@jennyq seems safe to close?

**Comment by jennyq** [comment]
Thanks! Done.
