### ISSUE TITLE
SITE_SETTINGS_KEY documentation for Tendenci 8 misleading?

### ISSUE THREAD

**Issue by replaceafill** [tendenci/tendenci#670]
Disclaimer: English is not my first language so I may be misinterpreting this or missing something.

From the [Tendenci8 installation doc](https://github.com/tendenci/tendenci/blob/tendenci8/docs/source/installation/installation.txt#L230-L231):

> Set ``SECRET_KEY`` and ``SITE_SETTINGS_KEY`` to random strings 50 characters in length.

And from the `conf/settings.py` module in the tendenci8 branch of the project template:

> These must be set to two different random 50-character strings that are unique                                                                                   

If I set `SITE_SETTINGS_KEY` to `12345678901234567890123456789012345678901234567890` and try to set the Site URL:

```bash
$ python tendenci/manage.py set_setting site global siteurl 'https://www.example.com'
```
I get this error:

```python
Traceback (most recent call last):
  File "tendenci/manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/tendenci/apps/site_settings/management/commands/set_setting.py", line 30, in handle
    setting.set_value(value)
  File "/usr/local/lib/python3.6/site-packages/tendenci/apps/site_settings/models.py", line 52, in set_value
    self.value = encrypt(value)
  File "/usr/local/lib/python3.6/site-packages/tendenci/apps/site_settings/crypt.py", line 13, in encrypt
    cipher = AES.new(settings.SITE_SETTINGS_KEY.encode(), AES.MODE_ECB)
  File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 200, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 55, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/_mode_ecb.py", line 177, in _create_ecb_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 90, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (50 bytes)
```

I think this is the same case discussed here https://github.com/tendenci/tendenci/issues/364#issuecomment-85704355

If I set `SITE_SETTINGS_KEY` to `12345678901234567890123456789012` the set_setting command works.

PS: Thank you very much for the great work you're doing with the Tendenci 8 branch. I just discovered Django 1.8 support ends officially today, and noticed all the work you've been doing on this lately. I'm testing it for the first time and plan to migrate our instances in the near future.

**Comment by PaulSD** [comment]
Good catch!  Fixed in https://github.com/PaulSD/tendenci/commit/c1f00dafdc047720ea30b04e513c74b8f23b2ead and https://github.com/PaulSD/tendenci-project-template/commit/7ed0358b403152e5f1b837b568c0775ef3ecd845

**Comment by BenSturmfels** [comment]
@jennyq I think this is safe to close

**Comment by jennyq** [comment]
Thanks!
