### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xab in position 0: ordinal not in range

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#682]
Following a recent update (still running Tendenci 7.4.4, python 2.7.6, perhaps a dependency updated?) I'm now seeing the following error - can you suggest a possible cause/solution?

```
root@tendenci-combined:/srv/tendenci/website# python manage.py clear_cache
2018-04-28 20:40:18 WARNING py.warnings: /usr/local/lib/python2.7/dist-packages/tendenci/apps/base/fields.py:153: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if initial_choices_keys and initial_choices_keys != u'[]':

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/profiles/admin.py", line 10, in <module>
    from tendenci.apps.profiles.forms import ProfileAdminForm
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/profiles/forms.py", line 100, in <module>
    class ProfileForm(TendenciBaseForm):
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/profiles/forms.py", line 136, in ProfileForm
    country = CountrySelectField(label=_("Country"), required=False)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/base/fields.py", line 157, in __init__
    initial_choices = tuple(initial_choices) + (('','-----------'),)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/base/fields.py", line 154, in <genexpr>
    initial_choices =  ((name, name) for key, name in list(COUNTRIES) if key in initial_choices_keys)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xab in position 0: ordinal not in range(128)
```

**Comment by goetzk** [comment]
I looked in to this further, adding the following debug to CountrySelectField:

```
class CountrySelectField(fields.ChoiceField):
    def __init__(self, *args, **kwargs):
        super(CountrySelectField, self).__init__(*args, **kwargs)
        
        initial_choices = ()
        exclude_list = []
        
        initial_choices_keys = get_setting('site', 'global', 'countrylistinitialchoices')
        print 'initial choices keys is %s' %  type(initial_choices_keys)
        print initial_choices_keys
        print 'initial choices is %s' % type(initial_choices)
        print initial_choices
        print 'we are comparing with %s' % type(u'[]')
        print ''
        if initial_choices_keys and initial_choices_keys != u'[]':
            print 'COUNTRIES is %s' % type(COUNTRIES)
            print COUNTRIES
            initial_choices =  ((name, name) for key, name in list(COUNTRIES) if key in initial_choices_keys)
            exclude_list = initial_choices_keys
[...]
```

Which led to this output.

```
root@tendenci-combined:/srv/tendenci/website# python2.7 manage.py clear_cache
initial choices keys is <type 'str'>
??h???B'???DI??=JE??????]2&?aƇ?w?P??p?????]??'???K
q2??
initial choices is <type 'tuple'>
()
we are comparing with <type 'unicode'>

2018-05-07 20:38:55 WARNING py.warnings: /usr/local/lib/python2.7/dist-packages/tendenci/apps/base/fields.py:159: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if initial_choices_keys and initial_choices_keys != u'[]':

COUNTRIES is <class 'django_countries.Countries'>
<django_countries.Countries object at 0x7f32cc31ded0>
initial choices keys is <type 'str'>
??h???B'???DI??=JE??????]2&?aƇ?w?P??p?????]??'???K
q2??
initial choices is <type 'tuple'>
()
we are comparing with <type 'unicode'>

COUNTRIES is <class 'django_countries.Countries'>
<django_countries.Countries object at 0x7f32cc31ded0>
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/profiles/admin.py", line 10, in <module>
    from tendenci.apps.profiles.forms import ProfileAdminForm
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/profiles/forms.py", line 87, in <module>
    class ProfileForm(TendenciBaseForm):
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/profiles/forms.py", line 123, in ProfileForm
    country = CountrySelectField(label=_("Country"), required=False)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/base/fields.py", line 165, in __init__
    initial_choices = tuple(initial_choices) + (('','-----------'),)
  File "/usr/local/lib/python2.7/dist-packages/tendenci/apps/base/fields.py", line 162, in <genexpr>
    initial_choices =  ((name, name) for key, name in list(COUNTRIES) if key in initial_choices_keys)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xab in position 0: ordinal not in range(128)
```

Setting initial_choices_keys to '' got things running again.

        initial_choices_keys = '' # get_setting('site', 'global', 'countrylistinitialchoices')

Is there some way validity checking can be added?

**Comment by jennyq** [comment]
Maybe the setting is corrupted in the database? Try to reset the value by running the command below to see if that fixes the error:

    python manage.py set_setting site global countrylistinitialchoices ['AU']

**Comment by jennyq** [comment]
Hold on, don't run that command - it doesn't work..

**Comment by jennyq** [comment]
Try this one:

    python manage.py set_setting site global countrylistinitialchoices "['AU']"

**Comment by goetzk** [comment]
I tracked down the root cause: SECRET_KEY and SITE_SETTINGS_KEY had changed (why, I'm not totally sure).
