### ISSUE TITLE
Incomplete files migration

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#708]
Related to #706 (where I had to create files.0005*) I had to update the migration to resolve a schema issue.

```
(testsuite_venv)root@tendenci-combined:/srv/testsuite-tendenci/tendenci_testsite# time coverage run --branch manage.py test --verbosity 2 --keepdb
/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For detai
ls see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Using existing test database for alias 'default' ('test_tendenci_testsuite')...
Operations to perform:
  Synchronize unmigrated apps: django_admin_bootstrapped, debug_toolbar, tendenci, accounts, formtools, bootstrapform, bootstrap3, gis, api_tasty, tinymce, markdown_deux, djkombu, theme, humanize, haystack, model_report, gunicorn, tags, staticfiles, sitemaps, registry, uploader, mobile, admindocs, messages, social_media, dj_pagination, styled_forms
  Apply all migrations: staff, accountings, redirects, videos, invoices, imports, locations, email_blocks, captcha, navs, meta, explorer_extensions, registration, stories, case_studies, user_groups, contributions, payments, industries, regions, speakers, entities, contacts, event_logs, forums, helpdesk, tastypie, sites, corporate_memberships, pages, forms, discounts, contenttypes, wp_importer, tagging, site_settings, theme_editor, ics, announcements, social_services, events, careers, make_payments, files, studygroups, exports, newsletters, jobs, explorer, sessions, robots, auth, educations, metrics, notifications, boxes, base, campaign_monitor, tendenci_guide, news, wp_exporter, emails, categories, articles, search, committees, handler404, photos, admin, perms, directories, versions, djcelery, social_auth, profiles, recurring_payments, memberships, reports, testimonials, donations, dashboard, resumes, help_files, stripe
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying files.0005_auto_20180626_2307...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python2.7/dist-packages/django/test/runner.py", line 210, in run_tests
    old_config = self.setup_databases()
  File "/usr/local/lib/python2.7/dist-packages/django/test/runner.py", line 166, in setup_databases
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/django/test/runner.py", line 370, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/creation.py", line 368, in create_test_db
    test_flush=not keepdb,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 484, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/schema.py", line 113, in _alter_field
    new_db_params, strict,
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 567, in _alter_field
    new_default = self.effective_default(new_field)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 198, in effective_default
    default = field.get_default()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 1947, in get_default
    field_default = super(ForeignKey, self).get_default()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 794, in get_default
    return self.default()
  File "/srv/testsuite-tendenci/src/tendenci/tendenci/apps/user_groups/utils.py", line 39, in get_default_group
    return Group.objects.get_initial_group_id()
  File "/srv/testsuite-tendenci/src/tendenci/tendenci/apps/user_groups/managers.py", line 61, in get_initial_group_id
    group = self.get_or_create_default()
  File "/srv/testsuite-tendenci/src/tendenci/tendenci/apps/user_groups/managers.py", line 50, in get_or_create_default
    group = self.create(**params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/srv/testsuite-tendenci/src/tendenci/tendenci/apps/user_groups/models.py", line 79, in save
    super(Group, self).save(force_insert, force_update, *args, **kwargs)
  File "/srv/testsuite-tendenci/src/tendenci/tendenci/apps/perms/models.py", line 115, in save
    super(TendenciBaseModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/srv/testsuite-tendenci/src/tendenci/tendenci/apps/search/signals.py", line 47, in enqueue_save
    save_unindexed_item(sender, **kwargs)
  File "/srv/testsuite-tendenci/src/tendenci/tendenci/apps/search/signals.py", line 20, in save_unindexed_item
    if not UnindexedItem.objects.filter(**params).exists():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 586, in exists
    return self.query.has_results(using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 484, in has_results
    return compiler.has_results()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 811, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "search_unindexeditem" does not exist
LINE 1: SELECT (1) AS "a" FROM "search_unindexeditem" WHERE ("search...
                               ^


real    24m14.312s
user    24m0.108s
sys     0m10.864s
```

The required change was adding 'search' to the dependencies:

```
    dependencies = [
        ('files', '0004_auto_20180315_0857'),
        ('search', '0001_initial'),
    ]
```

Does this sound like a reasonable change to you too? should the dependency be added to an earlier files entry?

**Comment by goetzk** [comment]
This was never responded to but I assume at this stage whatever issue was exposed will have been fixed in later development.
