### ISSUE TITLE
STRIPE ERROR

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#758]
I started getting this error lately in T7 websites
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/whapl/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/whapl/local/lib/python2.7/site-packages/tendenci/apps/payments/stripe/views.py", line 230, in pay_online
    params.update({'card': token})
UnboundLocalError: local variable 'token' referenced before assignment

Any ideas? It was not happening before.

**Comment by jennyq** [comment]
@dco5, looks like stripe didn't pass over the token for some reason. I've pushed out a fix https://github.com/tendenci/tendenci/commit/e87cae59e5fd5725ab680f5c01ea642cefcf5b64, which should stop this error. Then, probably you can discover the real issue behind it.

**Comment by eschipul** [comment]
Closing issue. Please reopen if this did not resolve the issue.
