### ISSUE TITLE
python manage.py initial_migrate not running

### ISSUE THREAD

**Issue by seato10** [tendenci/tendenci#789]
Followed the install guide on ubuntu 18.04 exactly and keep getting stuck here. Can't figure out the issue, so was wondering if anyone else has experienced this?

/var/www/mysite$ python manage.py migrate
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/config.py", line 565, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.6/logging/config.py", line 738, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/tendenci/debug.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/mysite/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/mysite/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/srv/mysite/lib/python3.6/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/srv/mysite/lib/python3.6/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.6/logging/config.py", line 802, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.6/logging/config.py", line 573, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'debug_file': [Errno 2] No such file or directory: '/var/log/tendenci/debug.log'

**Comment by eschipul** [comment]
Can you try

sudo mkdir -p /var/log/tendenci 
sudo touch /var/log/tendenci/debug.log

Then run initial again. 

If that works I’ll update the docs

**Comment by benbowc** [comment]
This sorts the debug.log issue but there is now a syntax error in manage.py
![image](https://user-images.githubusercontent.com/41653422/61677643-75662f80-ad54-11e9-8298-960291fa1a84.png)

**Comment by jennyq** [comment]
Hi @benbowc, 
Have you sort it out? You were probably running Python 2 because the exception chaining only works in Python 3.

**Comment by EdzonQS** [comment]
Hey @benbowc,
 The first error raises up because you don't have tendenci directory in /var/log/
the second error 
the File "manage.py", line 18
    ) from exc
SyntaxError: invalid syntax 
It's because you forgot to activate your venv(virtual environment)
