### ISSUE TITLE
Error in membership application

### ISSUE THREAD

**Issue by avkovalevs** [tendenci/tendenci#797]
Hello @jennyq 
When I add a member to the "basic membership application" error happens with Sexe filed.
The basic membership application uses a french language. 
![Screenshot_error_with_MF](https://user-images.githubusercontent.com/22083701/61615103-e1ba3380-ac6d-11e9-853f-b3f06bd6ccc3.png)
I have also another membership application (New membership alumni). It uses an EN  lang.
This form (alumni) working without any errors.
How can I fix form with Fr lang?

**Comment by jennyq** [comment]
Good catch! It is because the available choices are 'male' and 'female' https://github.com/tendenci/tendenci/blob/master/tendenci/apps/profiles/models.py#L61. We'll need to think about this one but will come up with something to get the issue resolved.

**Comment by avkovalevs** [comment]
@jennyq Maybe you have an idea how to resolve it faster?

**Comment by jennyq** [comment]
Yes, I do have a workaround. I'm thinking to have an option to specify both name and display name separated by a colon like this `'male:Masculin,female:Feminin, :Autre'`. What do you think?

**Comment by avkovalevs** [comment]
When I changed the tendenci/apps/memberships/models.py my gunicorn server not started.
[2019-07-25 14:56:22 -0500] [14582] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/var/www/mysite/conf/wsgi.py", line 19, in <module>
    application = get_wsgi_application()
  File "/srv/mysite/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/srv/mysite/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/mysite/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/srv/mysite/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/srv/mysite/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/srv/mysite/lib/python3.6/site-packages/tendenci/apps/memberships/models.py", line 2614
    field_args["choices"] = list(zip(choices, choices))
ndentationError: unexpected indent
[2019-07-25 14:56:22 -0500] [14582] [INFO] Worker exiting (pid: 14582)
Traceback (most recent call last):
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 210, in run
    self.sleep()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 360, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/mysite/bin/gunicorn", line 10, in <module>
    sys.exit(run())
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 232, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 345, in halt
    self.stop()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/srv/mysite/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

**Comment by avkovalevs** [comment]
I changed only the row 2614

**Comment by avkovalevs** [comment]
File "/srv/mysite/lib/python3.6/site-packages/tendenci/apps/memberships/models.py", line 2615
    field_args["choices"] = [(s.split(':')[0].strip(), s.split(':')[-1].strip()) for s in choices]
    ^
IndentationError: unexpected indent

**Comment by avkovalevs** [comment]
I used a new row
field_args["choices"] = [(s.split(':')[0].strip(), s.split(':')[-1].strip()) for s in choices]
and returned old row
field_args["choices"] = list(zip(choices, choices))
In both cases junicorn failed

**Comment by avkovalevs** [comment]
Sorry, I've find the reason.

**Comment by avkovalevs** [comment]
@jennyq 
I added the row 'male:Masculin,female:Feminin, :Autre' on the Fields page -> field Choices.
But this is not working correctly.
By default this looking like a checkbox with values 'male' or 'female'. When I add this row  It is looking like Textbox without any choice.

**Comment by jennyq** [comment]
You can select either "Drop Down" or "Radio Buttons" as Field Type for that field. If the field type is "Text", the specified choices wouldn't take effect.

**Comment by avkovalevs** [comment]
Ok, thanks
