### ISSUE TITLE
manage.py list_tables is broken

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#901]
Latest tendenci 
```
$ pip show tendenci
Name: tendenci
Version: 12.2.8
Summary: Tendenci - The Open Source Association Management System (AMS)
Home-page: https://github.com/tendenci/tendenci/
Author: Tendenci
Author-email: programmers@tendenci.com
License: GPL3
Location: /data/venv/tendenci/lib/python3.8/site-packages
Requires: unidecode, django-debug-toolbar, nameparser, django-bootstrap3, pisa, XlsxWriter, xhtml2pdf, createsend, xlrd, django-authority, bleach, django-simple-captcha, django-annoying, python-dateutil, stripe, Pillow, oauth2, django-ses, django-bootstrap-form, psycopg2, xlwt, Django, django-formtools, six, docutils, django-storages, chardet, configparser, django-localflavor, django-tagging, django-tastypie, simple-salesforce, beautifulsoup4, boto3, django-app-namespace-template-loader, Markdown, django-form-utils, pycryptodome, Authlib, celery, mimeparse, django-markdown-deux, Whoosh, unicodecsv, gevent, future, django-countries, django-nocaptcha-recaptcha, Embedly, webcolors, python-magic, django-picklefield, django-sql-explorer, django-timezone-field, dj-pagination, gunicorn, feedparser, simplejson, anyjson, pdfminer.six, tendenci-django-admin-bootstrapped, django-haystack, email-reply-parser, raven, pytz, selenium
Required-by: 
```
and:

```
$ python manage.py list_tables
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/venv/tendenci/lib/python3.8/site-packages/tendenci/apps/base/management/commands/list_tables.py", line 4, in <module>
    from django.db.models import get_models, get_app
ImportError: cannot import name 'get_models' from 'django.db.models' (/data/venv/tendenci/lib/python3.8/site-packages/django/db/models/__init__.py)
```
Seems as if it's not been maintained with the Django version. And so:

```
$ pip show django
Name: Django
Version: 2.2.16
Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Home-page: https://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD
Location: /data/venv/tendenci/lib/python3.8/site-packages
Requires: pytz, sqlparse
Required-by: tendenci, tendenci-django-admin-bootstrapped, django-timezone-field, django-storages, django-sql-explorer, django-simple-captcha, django-ses, django-ranged-response, django-picklefield, django-localflavor, django-haystack, django-formtools, django-debug-toolbar, django-bootstrap-form, django-authority, django-annoying
```

Itself mildly surprising given how long Django 3 has been out. But fine. I'm guessing Django 2.2.16 no longer has a get_models function to offer in this way.

**Comment by bernd-wechner** [comment]
Thanks heaps!
