### ISSUE TITLE
"relation "files_multiplefile" does not exist" when attempting dumpdata

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#912]
Here is what I am experiencing:

```
$ python manage.py dumpdata -v 2 --traceback > demo.json
Traceback (most recent call last):
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "files_multiplefile" does not exist
LINE 1: ...TH HOLD FOR SELECT "files_multiplefile"."id" FROM "files_mul...
```
It's not much to go on, so I'm posting an issue here in the hope it rings a bell with someone more experience.

If I do this:

```
grep -R files_multiplefile *
```

in my tendenci venv it returns nothing. Likewise in my project folder. Which is itself puzzling.

it has the hallmarks of relating to the file app, and checking its `models.py` indeed there is no `files_multiplefile` model at all, but then nor is there a reference to one anywhere in the code base including migrations etc. So a deep puzzle or coincidental naming similarity and something else relates.

The whole out with DEBUG=True in settings.py is:

```
$ python manage.py dumpdata -v 2 --traceback > demo2.json
/data/venv/tendenci/lib/python3.8/site-packages/captcha/conf/settings.py:34: DeprecationWarning: CAPTCHA_OUTPUT_FORMAT setting is deprecated in favor of widget's template_name.
  warnings.warn(msg, DeprecationWarning)

/data/venv/tendenci/lib/python3.8/site-packages/django/urls/resolvers.py:182: FutureWarning: Possible nested set at position 24
  return re.compile(regex)

Traceback (most recent call last):
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "files_multiplefile" does not exist
LINE 1: ...TH HOLD FOR SELECT "files_multiplefile"."id" FROM "files_mul...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "files_multiplefile" does not exist
LINE 1: ...TH HOLD FOR SELECT "files_multiplefile"."id" FROM "files_mul...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/management/commands/dumpdata.py", line 181, in handle
    serializers.serialize(
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/serializers/__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/serializers/base.py", line 90, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/management/commands/dumpdata.py", line 169, in get_objects
    yield from queryset.iterator()
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/models/query.py", line 341, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1145, in execute_sql
    cursor.close()
psycopg2.errors.InvalidCursorName: cursor "_django_curs_140377333020480_21" does not exist
```

I would love to see this reolved or at least understood. It is sugfgestive of data integrity issues afyer all.

**Comment by jennyq** [comment]
The MultipleFile is a model that is not managed, meaning there is no database table created. https://github.com/tendenci/tendenci/blob/master/tendenci/apps/files/models.py#L379

Exclude it with `--exclude=files.multiplefile`

**Comment by bernd-wechner** [comment]
Thanks for the tip Jenny! Puzzlingly a cascade of similar issues emerges. 

This:

`python manage.py dumpdata --exclude=files.multiplefile -v 2 --traceback `

crashes with:

```
psycopg2.errors.UndefinedTable: relation "events_standardregform" does not exist
```
which also an umanaged form.

So then:

`python manage.py dumpdata --exclude=files.multiplefile --explude=events_standardregform -v 2 --traceback`

crashes with:

```
psycopg2.errors.UndefinedTable: relation "mig_help_files_helpfile_t4_to_t5" does not exist
```

which is a migration and odd that that's even relevant, ut checking the first mirgation in the hel_files app and yes that table is marked unmanaged.

But then I'm stuck guessing at the exclude syntax. And starting to feel this is a dumpdata issue with Django to follow up there, arguing dumpdata should simply ignore unmanaged models!

**Comment by jennyq** [comment]
I agree with you on that dumpdata should simply ignore unmanaged models. There is a  django issue on that subject https://code.djangoproject.com/ticket/13816. But it is marked as "wontfix".
