### ISSUE TITLE
Error while sending notifications for events

### ISSUE THREAD

**Issue by AdamBark** [tendenci/tendenci#922]
I've been getting the following error at event registration which has caused several people to repeat registration and get charged again. I think the problem might come from apps/notifications/models/NoticeEmail; the emails field is CharField with max_length=200 and the admin notice emails list consists of the set of all admin notice recipients from the global settings and the admin notice recipients for the payments module. I'm not sure if it's a bug but it fails in not the most obvious way and there's no notice that the number of emails is severly limited.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(200)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tendenci/apps/payments/stripe/views.py", line 293, in pay_online
    send_payment_notice(request, payment)
  File "/usr/local/lib/python3.6/dist-packages/tendenci/apps/payments/utils.py", line 95, in send_payment_notice
    'payment_added', notif_context)
  File "/usr/local/lib/python3.6/dist-packages/tendenci/apps/notifications/utils.py", line 13, in send_notifications
    send_emails(recipients, label, extra_context)
  File "/usr/local/lib/python3.6/dist-packages/tendenci/apps/notifications/models.py", line 456, in send_emails
    notice_type=notice_type
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.6/dist-packages/tendenci/apps/notifications/models.py", line 215, in save
    super(NoticeEmail, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 744, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 782, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 911, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(200)
```

**Comment by jennyq** [comment]
Resolved https://github.com/tendenci/tendenci/commit/f4057ba7472f3fdb72a9118b2498c554fe53d88d. The max_length of emails field is also increased to 300. 

Thanks @AdamBark for reporting it!
