### ISSUE TITLE
Site is down: TypeError: 'Setting' object is not iterable

### ISSUE THREAD

**Issue by bernd-wechner** [tendenci/tendenci#995]
Our site is down today, well it sort of loads, but is seriously broken. No images on the public site, and on a logged in page nothing at bar a dysfunctional top menu, with a console complaint that it can't load bootstrap).

This is all that is in the log after a restart of the server by way of a clue. 

I'm looking into it now. But as out site is down, I wanted greedily to send out a feeler in case someone has any tips on what might have gone wrong here. Of course I am looking right now into get_theme_search_order ...

```
Traceback (most recent call last):
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/venv/tendenci/lib/python3.8/site-packages/tendenci/apps/base/views.py", line 279, in homepage
    return render_to_resp(request=request, template_name=template_name)
  File "/data/venv/tendenci/lib/python3.8/site-packages/tendenci/apps/theme/shortcuts.py", line 43, in themed_response
    rendered = template.render(context=context, request=request)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/data/venv/tendenci/lib/python3.8/site-packages/django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/data/venv/tendenci/lib/python3.8/site-packages/debug_toolbar/panels/templates/panel.py", line 46, in _request_context_bind_template
    context = processor(self.request)
  File "/data/venv/tendenci/lib/python3.8/site-packages/tendenci/apps/base/context_processors.py", line 11, in static_url
    context['TINYMCE_JS_URL'] = static(settings.TINYMCE_JS_URL)
  File "/data/venv/tendenci/lib/python3.8/site-packages/tendenci/apps/theme/templatetags/static.py", line 115, in static
    return ThemeStaticNode.handle_simple(path, local_only)
  File "/data/venv/tendenci/lib/python3.8/site-packages/tendenci/apps/theme/templatetags/static.py", line 53, in handle_simple
    for cur_theme in get_theme_search_order(theme):
TypeError: 'Setting' object is not iterable
```

**Comment by bernd-wechner** [comment]
Resolved. Not understood alas. I was in process of drilling down into get_theme_search_order to work out why it's returning a Setting object when I noticed something else broken somewhere else (which had in common with this site a gateway router). So I rebooted the gateway router, and this issue disappeared. 

A puzzle as I've checked the gateway router configs and it does nothing but forward to the respective server (reverse proxy) non selective (as in there is a single path for the static files and everything else ....).
